### PR TITLE
NoSQL: filter ACL entries by direction in loadGrants

### LINKED ISSUE #4219: Bug: Unexpected entity type 'CATALOG_ROLE' error in listGrantsForCatalogRole with grants containing CATALOG_ROLE as securable
### Describe the bug

Calling `GET /api/management/v1/catalogs/{catalogName}/catalog-roles/{catalogRoleName}/grants` results in a 400 error when a grant record exists for a catalogRole where the grant's securable entity is of type `CATALOG_ROLE`. The `default` case in the switch statement in `listGrantsForCatalogRole` throws an `IllegalArgumentException` because only `CATALOG`, `NAMESPACE`, `TABLE_LIKE`, and `POLICY` are handled — `CATALOG_ROLE` is not. See the code sample in the description.

### To Reproduce

1. Create a new catalog (the catalog role `catalog_admin` will be added automatically by system)
2. Call the management API endpoint `/api/management/v1/catalogs/{catalogName}/catalog-roles/catalog_admin/grants`
3. Observe the HTTP 400 and the corresponding error log.

#### Full HTTP response

```json
{
  "error": {
    "message": "Unexpected entity type 'CATALOG_ROLE' listing grants for catalogRole 'catalog_admin' in catalog 'test'",
    "type": "IllegalArgumentException",
    "code": 400
  }
}
```

#### Debug log output

```
2026-04-16 04:33:23,361 DEBUG [io.qua.ver.htt.run.ForwardedParser] [,] [,,,] (vert.x-eventloop-thread-0) Recalculated absoluteURI to http://localhost:8181/api/management/v1/catalogs/test/catalog-roles/catalog_admin/grants
2026-04-16 04:33:23,362 DEBUG [io.qua.mic.run.bin.ver.VertxHttpServerMetrics] [,] [,,,] (vert.x-eventloop-thread-0) requestRouted null HttpRequestMetric [initialPath=/api/management/v1/catalogs/test/catalog-roles/catalog_admin/grants, currentRoutePath=null, templatePath=null, request=io.vertx.core.http.impl.Http1xServerRequest@2e2f01df]
2026-04-16 04:33:23,362 DEBUG [io.qua.mic.run.bin.ver.VertxHttpServerMetrics] [,] [,,,] (vert.x-eventloop-thread-0) requestRouted null HttpRequestMetric [initialPath=/api/management/v1/catalogs/test/catalog-roles/catalog_admin/grants, currentRoutePath=null, templatePath=null, request=io.vertx.core.http.impl.Http1xServerRequest@2e2f01df]
2026-04-16 04:33:23,362 DEBUG [io.qua.mic.run.bin.ver.VertxHttpServerMetrics] [,] [,,,] (vert.x-eventloop-thread-0) requestRouted null HttpRequestMetric [initialPath=/api/management/v1/catalogs/test/catalog-roles/catalog_admin/grants, currentRoutePath=null, templatePath=null, request=io.vertx.core.http.impl.Http1xServerRequest@2e2f01df]
2026-04-16 04:33:23,362 DEBUG [io.qua.mic.run.bin.ver.VertxHttpServerMetrics] [,] [,,,] (vert.x-eventloop-thread-0) requestRouted null HttpRequestMetric [initialPath=/api/management/v1/catalogs/test/catalog-roles/catalog_admin/grants, currentRoutePath=null, templatePath=null, request=io.vertx.core.http.impl.Http1xServerRequest@2e2f01df]
2026-04-16 04:33:23,362 DEBUG [io.qua.mic.run.bin.ver.VertxHttpServerMetrics] [,] [,,,] (vert.x-eventloop-thread-0) requestRouted null HttpRequestMetric [initialPath=/api/management/v1/catalogs/test/catalog-roles/catalog_admin/grants, currentRoutePath=null, templatePath=null, request=io.vertx.core.http.impl.Http1xServerRequest@2e2f01df]
2026-04-16 04:33:23,362 DEBUG [io.qua.mic.run.bin.ver.VertxHttpServerMetrics] [,] [,,,] (vert.x-eventloop-thread-0) requestRouted null HttpRequestMetric [initialPath=/api/management/v1/catalogs/test/catalog-roles/catalog_admin/grants, currentRoutePath=null, templatePath=null, request=io.vertx.core.http.impl.Http1xServerRequest@2e2f01df]
2026-04-16 04:33:23,362 DEBUG [io.qua.mic.run.bin.ver.VertxHttpServerMetrics] [,] [,,,] (vert.x-eventloop-thread-0) requestRouted null HttpRequestMetric [initialPath=/api/management/v1/catalogs/test/catalog-roles/catalog_admin/grants, currentRoutePath=null, templatePath=null, request=io.vertx.core.http.impl.Http1xServerRequest@2e2f01df]
2026-04-16 04:33:23,362 DEBUG [io.qua.mic.run.bin.ver.VertxHttpServerMetrics] [,] [,,,] (vert.x-eventloop-thread-0) requestRouted null HttpRequestMetric [initialPath=/api/management/v1/catalogs/test/catalog-roles/catalog_admin/grants, currentRoutePath=null, templatePath=null, request=io.vertx.core.http.impl.Http1xServerRequest@2e2f01df]
2026-04-16 04:33:23,362 DEBUG [io.qua.mic.run.bin.ver.VertxHttpServerMetrics] [,] [,,,] (vert.x-eventloop-thread-0) requestRouted null HttpRequestMetric [initialPath=/api/management/v1/catalogs/test/catalog-roles/catalog_admin/grants, currentRoutePath=null, templatePath=null, request=io.vertx.core.http.impl.Http1xServerRequest@2e2f01df]
2026-04-16 04:33:23,362 DEBUG [io.qua.mic.run.bin.ver.VertxHttpServerMetrics] [,] [,,,] (vert.x-eventloop-thread-0) requestRouted / HttpRequestMetric [initialPath=/api/management/v1/catalogs/test/catalog-roles/catalog_admin/grants, currentRoutePath=null, templatePath=null, request=io.vertx.core.http.impl.Http1xServerRequest@2e2f01df]
2026-04-16 04:33:23,363 DEBUG [io.qua.ver.htt.run.RoutingUtils] [c1686046-0ca1-41ca-b4fd-ea19577d6ce3_0000000000000089474,POLARIS] [,,,] (executor-thread-235) CDI request context owner has changed from 'quarkus-rest' to 'quarkus-rest'
2026-04-16 04:33:23,371 INFO  [org.apa.pol.ser.exc.IcebergExceptionMapper] [c1686046-0ca1-41ca-b4fd-ea19577d6ce3_0000000000000089474,POLARIS] [,,,] (executor-thread-235) Handling runtimeException Unexpected entity type 'CATALOG_ROLE' listing grants for catalogRole 'catalog_admin' in catalog 'test'
2026-04-16 04:33:23,372 INFO  [io.qua.htt.access-log] [c1686046-0ca1-41ca-b4fd-ea19577d6ce3_0000000000000089474,POLARIS] [,,,] (executor-thread-235) 127.0.0.1 - root [16/Apr/2026:04:33:23 +0000] "GET /api/management/v1/catalogs/test/catalog-roles/catalog_admin/grants HTTP/1.1" 400 171
2026-04-16 04:33:23,372 DEBUG [io.qua.mic.run.bin.ver.VertxHttpServerMetrics] [,] [,,,] (vert.x-eventloop-thread-0) responseEnd io.vertx.core.http.impl.Http1xServerResponse@35bdb404, HttpRequestMetric [initialPath=/api/management/v1/catalogs/test/catalog-roles/catalog_admin/grants, currentRoutePath=/, templatePath=null, request=io.vertx.core.http.impl.Http1xServerRequest@2e2f01df]
```

### Actual Behavior

400 HTTP error with message:

    Unexpected entity type 'CATALOG_ROLE' listing grants for catalogRole ...

### Expected Behavior

Polaris should skip or ignore grants with an unknown entity type instead of failing, or at least log a warning.
Result: No HTTP 400, API continues to return only valid grants.

### Additional context

See full function: https://github.com/apache/polaris/blob/main/runtime/service/src/main/java/org/apache/polaris/service/admin/PolarisAdminService.java#L2054-L2058

### System information

Polaris Catalog Version: 1.4.0-SNAPSHOT
Metastore Backend: MongoDB
OS: Rancher Desktop (Windows), AWS EKS (Linux nodes)

### PR DESCRIPTION
**Pull request by adutra**
Fixes #4219.

The NoSQL persistence layer stores both directional entry flavors in a single ACL document: reverse ('r/') entries where the entity is the grantee, and directed ('d/') entries where it is the securable. When loading grants for a specific perspective (grantee or securable), both flavors were returned, causing entities like `catalog_admin` — which appear as both grantee and securable — to produce incorrect grant records and trigger "Unexpected entity type 'CATALOG_ROLE'" errors.

## Checklist
- [ ] 🛡️ Don't disclose security issues! (contact security@apache.org)
- [ ] 🔗 Clearly explained why the changes are needed, or linked related issues: Fixes #
- [ ] 🧪 Added/updated tests with good coverage, or manually tested (and explained how)
- [ ] 💡 Added comments for complex logic
- [ ] 🧾 Updated `CHANGELOG.md` (if needed)
- [ ] 📚 Updated documentation in `site/content/in-dev/unreleased` (if needed)

### CODE REVIEW

File: persistence/nosql/persistence/metastore/src/main/java/org/apache/polaris/persistence/nosql/metastore/NoSqlMetaStore.java [hunk 1]
```diff
@@ -1148,11 +1148,17 @@ LoadGrantsResult loadGrants(long catalogId, long id, int entityTypeCode, boolean
     var collector = new GrantRecordsCollector();
     var entities = new ArrayList<PolarisBaseEntity>();
     var ids = new HashSet<Long>();
+    // ACLs for a given entity contain two directional entry flavors:
+    //   - reverse ('r/...'): grants where that entity is the grantee
+    //   - directed ('d/...'): grants where that entity is the securable
+    // Filter by direction so callers receive only the requested perspective.
+    Predicate<GrantTriplet> entryFilter =
+        onSecurable ? triplet -> !triplet.reverseOrKey() : GrantTriplet::reverseOrKey;
```
Comment (dimas-b) [inline persistence/nosql/persistence/metastore/src/main/java/org/apache/polaris/persistence/nosql/metastore/NoSqlMetaStore.java:1156]:
```suggestion
    Predicate<GrantTriplet> entryFilter = GrantTriplet::reverseOrKey;
    entryFilter = onSecurable ? entryFilter.negate() : entryFilter;
```

**Review by snazy — APPROVED** [review]
LGTM!
Thanks for the fix!

**Review by dimas-b — APPROVED** [review]

**Review by flyrain — DISMISSED** [review]
LGTM

**Review by dimas-b — DISMISSED** [review]

**Comment by adutra** [comment]
Sorry folks there was a conflict and I had to rebase. Please re-approve! 🙏

**Review by dimas-b — APPROVED** [review]

**Comment by snazy** [comment]
Needs a rebase/merge-main after #4224
