### PR TITLE
Async Deletion of Previous Metadata and Statistics Files

### LINKED ISSUE #289: DROP TABLE with PURGE does not delete metadata.json files
### Is this a possible security vulnerability?

- [X] This is NOT a possible security vulnerability

### Describe the bug

When dropping a table, the data folder is deleted but the metadata folder remains with the metadata.json files it contains.

### To Reproduce

Using postgres as the metadata store, and GCS for storage.

The queries below (executed in Trino) create a schema/namespace in the catalog, creates a table from some sample data in BigQuery(the data can be from anywhere really), copies the data to a second table, then drops the second table.

```
CREATE SCHEMA IF NOT EXISTS polarisgcs.test_schema1 WITH (location = 'gs://bucket-iceberg-polaris/polaris/test_schema1');

CREATE TABLE IF NOT EXISTS polarisgcs.test_schema1.test1 WITH (format='PARQUET', partitioning = ARRAY['domain_id', 

'day(date)']) AS SELECT date, domain_id, country, resource_id, metric1 FROM bq.sample.table1;

CREATE TABLE IF NOT EXISTS polarisgcs.test_schema1.test2 WITH (format='PARQUET', partitioning = ARRAY['domain_id', 'day(date)']) AS SELECT date, domain_id, country, resource_id, metric1 FROM polarisgcs.test_schema1.test1;

DROP TABLE polarisgcs.test_schema1.test2;
```

### Actual Behavior

files in `{table name}/metadata`  are not deleted
```
>gsutil ls gs://bucket-iceberg-polaris/polaris/test_schema1/test2*/**
gs://bucket-iceberg-polaris/polaris/test_schema1/test2-139045f9cbde4d1f9ef643141621a208/metadata/00000-af991efc-4628-4703-95c4-338a721eada7.metadata.json
gs://bucket-iceberg-polaris/polaris/test_schema1/test2-139045f9cbde4d1f9ef643141621a208/metadata/20240912_202545_00006_ft2jx-d05107ef-d9c4-4021-a450-2ecb4c796c2f.stats
gs://bucket-iceberg-polaris/polaris/test_schema1/test2-139045f9cbde4d1f9ef643141621a208/metadata/snap-789093043791680477-1-f9449a04-12db-4360-a6fe-f577830d075a.avro
```

### Expected Behavior

All files in the dropped table's path are deleted.

### Additional context

postgres as backing metadata store
GCS storage

```{"timestamp":1726172836631,"level":"DEBUG","thread":"pool-3-thread-58 - DELETE /api/catalog/v1/polaris/namespaces/test_schema1/tables/test2?purgeRequested=true","logger":"org.apache.polaris.service.config.RealmEntityManagerFactory","message":"Looking up PolarisEntityManager for realm polaris_iceberg","mdc":{"spanId":"0da7f8369a5be134","traceId":"ad635ef2168e9224e25bcb4cfeb587b6","realm":"polaris_iceberg","request_id":null},"params":{}}
{"timestamp":1726172836631,"level":"INFO","thread":"pool-3-thread-58 - DELETE /api/catalog/v1/polaris/namespaces/test_schema1/tables/test2?purgeRequested=true","logger":"org.apache.polaris.service.auth.TestInlineBearerTokenPolarisAuthenticator","message":"Checking for existence of principal polarisTester in map {principal=polarisTester, realm=polaris_iceberg}","mdc":{"spanId":"0da7f8369a5be134","traceId":"ad635ef2168e9224e25bcb4cfeb587b6","realm":"polaris_iceberg","request_id":null},"params":{}}
{"timestamp":1726172836631,"level":"WARN","thread":"pool-3-thread-58 - DELETE /api/catalog/v1/polaris/namespaces/test_schema1/tables/test2?purgeRequested=true","logger":"org.apache.polaris.service.auth.TestInlineBearerTokenPolarisAuthenticator","message":"Failed to load secrets for principal polarisTester","mdc":{"spanId":"0da7f8369a5be134","traceId":"ad635ef2168e9224e25bcb4cfeb587b6","realm":"polaris_iceberg","request_id":null},"params":{}}
{"timestamp":1726172836631,"level":"DEBUG","thread":"pool-3-thread-58 - DELETE /api/catalog/v1/polaris/namespaces/test_schema1/tables/test2?purgeRequested=true","logger":"org.apache.polaris.service.auth.BasePolarisAuthenticator","message":"Resolving principal for tokenInfo client_id=null","mdc":{"spanId":"0da7f8369a5be134","traceId":"ad635ef2168e9224e25bcb4cfeb587b6","realm":"polaris_iceberg","request_id":null},"params":{}}
{"timestamp":1726172836631,"level":"DEBUG","thread":"pool-3-thread-58 - DELETE /api/catalog/v1/polaris/namespaces/test_schema1/tables/test2?purgeRequested=true","logger":"org.apache.polaris.service.config.RealmEntityManagerFactory","message":"Looking up PolarisEntityManager for realm polaris_iceberg","mdc":{"spanId":"0da7f8369a5be134","traceId":"ad635ef2168e9224e25bcb4cfeb587b6","realm":"polaris_iceberg","request_id":null},"params":{}}
{"timestamp":1726172836631,"level":"DEBUG","thread":"pool-3-thread-58 - DELETE /api/catalog/v1/polaris/namespaces/test_schema1/tables/test2?purgeRequested=true","logger":"org.apache.polaris.service.auth.BasePolarisAuthenticator","message":"Resolved principal: name=polarisTester;id=7;parentId=0;entityVersion=1;type=PRINCIPAL;subType=NULL_SUBTYPE;internalProperties={client_id=15454eed974a106b}","mdc":{"spanId":"0da7f8369a5be134","traceId":"ad635ef2168e9224e25bcb4cfeb587b6","realm":"polaris_iceberg","request_id":null},"params":{}}
{"timestamp":1726172836631,"level":"DEBUG","thread":"pool-3-thread-58 - DELETE /api/catalog/v1/polaris/namespaces/test_schema1/tables/test2?purgeRequested=true","logger":"org.apache.polaris.service.auth.BasePolarisAuthenticator","message":"Populating authenticatedPrincipal into CallContext: principalEntity=name=polarisTester;id=7;parentId=0;entityVersion=1;type=PRINCIPAL;subType=NULL_SUBTYPE;internalProperties={client_id=15454eed974a106b};activatedPrincipalRoleNames=[];activatedPrincipalRoles=null","mdc":{"spanId":"0da7f8369a5be134","traceId":"ad635ef2168e9224e25bcb4cfeb587b6","realm":"polaris_iceberg","request_id":null},"params":{}}
{"timestamp":1726172836633,"level":"DEBUG","thread":"pool-3-thread-58 - DELETE /api/catalog/v1/polaris/namespaces/test_schema1/tables/test2?purgeRequested=true","logger":"org.apache.polaris.service.catalog.api.IcebergRestCatalogApi","message":"Invoking CatalogApi with params","mdc":{"spanId":"0da7f8369a5be134","traceId":"ad635ef2168e9224e25bcb4cfeb587b6","realm":"polaris_iceberg","request_id":null},"params":{"purgeRequested":true,"prefix":"polaris","namespace":"test_schema1","operation":"dropTable","table":"test2"}}
{"timestamp":1726172836633,"level":"DEBUG","thread":"pool-3-thread-58 - DELETE /api/catalog/v1/polaris/namespaces/test_schema1/tables/test2?purgeRequested=true","logger":"org.apache.polaris.service.config.RealmEntityManagerFactory","message":"Looking up PolarisEntityManager for realm polaris_iceberg","mdc":{"spanId":"0da7f8369a5be134","traceId":"ad635ef2168e9224e25bcb4cfeb587b6","realm":"polaris_iceberg","request_id":null},"params":{}}
{"timestamp":1726172836633,"level":"DEBUG","thread":"pool-3-thread-58 - DELETE /api/catalog/v1/polaris/namespaces/test_schema1/tables/test2?purgeRequested=true","logger":"org.apache.polaris.core.auth.PolarisAuthorizer","message":"Satisfied privilege TABLE_DROP with grantRecord PolarisGrantRec{securableCatalogId=0, securableId=11, granteeCatalogId=11, granteeId=12, privilegeCode=31} from securable entity:name=polaris;id=11;parentId=0;entityVersion=1;type=CATALOG;subType=NULL_SUBTYPE;internalProperties={catalogType=INTERNAL, storage_configuration_info={\"@type\":\"GcpStorageConfigurationInfo\",\"allowedLocations\":[\"gs://bucket-iceberg-polaris/polaris\"],\"storageType\":\"GCS\",\"fileIoImplClassName\":\"org.apache.iceberg.gcp.gcs.GCSFileIO\"}};grantRecordsAsGrantee:[];grantRecordsAsSecurable:[PolarisGrantRec{securableCatalogId=0, securableId=11, granteeCatalogId=11, granteeId=12, privilegeCode=2}, PolarisGrantRec{securableCatalogId=0, securableId=11, granteeCatalogId=11, granteeId=12, privilegeCode=31}, PolarisGrantRec{securableCatalogId=0, securableId=11, granteeCatalogId=11, granteeId=12, privilegeCode=32}] for principalName polarisTester and activatedIds [2, 12]","mdc":{"spanId":"0da7f8369a5be134","traceId":"ad635ef2168e9224e25bcb4cfeb587b6","realm":"polaris_iceberg","request_id":null},"params":{}}
{"timestamp":1726172836633,"level":"DEBUG","thread":"pool-3-thread-58 - DELETE /api/catalog/v1/polaris/namespaces/test_schema1/tables/test2?purgeRequested=true","logger":"org.apache.polaris.core.auth.PolarisAuthorizer","message":"Satisfied privilege TABLE_WRITE_DATA with grantRecord PolarisGrantRec{securableCatalogId=0, securableId=11, granteeCatalogId=11, granteeId=12, privilegeCode=32} from securable entity:name=polaris;id=11;parentId=0;entityVersion=1;type=CATALOG;subType=NULL_SUBTYPE;internalProperties={catalogType=INTERNAL, storage_configuration_info={\"@type\":\"GcpStorageConfigurationInfo\",\"allowedLocations\":[\"gs://bucket-iceberg-polaris/polaris\"],\"storageType\":\"GCS\",\"fileIoImplClassName\":\"org.apache.iceberg.gcp.gcs.GCSFileIO\"}};grantRecordsAsGrantee:[];grantRecordsAsSecurable:[PolarisGrantRec{securableCatalogId=0, securableId=11, granteeCatalogId=11, granteeId=12, privilegeCode=2}, PolarisGrantRec{securableCatalogId=0, securableId=11, granteeCatalogId=11, granteeId=12, privilegeCode=31}, PolarisGrantRec{securableCatalogId=0, securableId=11, granteeCatalogId=11, granteeId=12, privilegeCode=32}] for principalName polarisTester and activatedIds [2, 12]","mdc":{"spanId":"0da7f8369a5be134","traceId":"ad635ef2168e9224e25bcb4cfeb587b6","realm":"polaris_iceberg","request_id":null},"params":{}}
{"timestamp":1726172836634,"level":"INFO","thread":"pool-3-thread-58 - DELETE /api/catalog/v1/polaris/namespaces/test_schema1/tables/test2?purgeRequested=true","logger":"org.apache.polaris.service.context.PolarisCallContextCatalogFactory","message":"Initializing new BasePolarisCatalog for key: polaris_iceberg/polaris","mdc":{"spanId":"0da7f8369a5be134","traceId":"ad635ef2168e9224e25bcb4cfeb587b6","realm":"polaris_iceberg","request_id":null},"params":{}}
{"timestamp":1726172836634,"level":"DEBUG","thread":"pool-3-thread-58 - DELETE /api/catalog/v1/polaris/namespaces/test_schema1/tables/test2?purgeRequested=true","logger":"org.apache.polaris.service.config.RealmEntityManagerFactory","message":"Looking up PolarisEntityManager for realm polaris_iceberg","mdc":{"spanId":"0da7f8369a5be134","traceId":"ad635ef2168e9224e25bcb4cfeb587b6","realm":"polaris_iceberg","request_id":null},"params":{}}
{"timestamp":1726172836634,"level":"INFO","thread":"pool-3-thread-58 - DELETE /api/catalog/v1/polaris/namespaces/test_schema1/tables/test2?purgeRequested=true","logger":"org.apache.polaris.service.context.PolarisCallContextCatalogFactory","message":"Looked up defaultBaseLocation gs://bucket-iceberg-polaris/polaris for catalog polaris_iceberg/polaris","mdc":{"spanId":"0da7f8369a5be134","traceId":"ad635ef2168e9224e25bcb4cfeb587b6","realm":"polaris_iceberg","request_id":null},"params":{}}
{"timestamp":1726172836634,"level":"DEBUG","thread":"pool-3-thread-58 - DELETE /api/catalog/v1/polaris/namespaces/test_schema1/tables/test2?purgeRequested=true","logger":"org.apache.polaris.service.catalog.BasePolarisCatalog","message":"Resolved ioImplClassName org.apache.iceberg.gcp.gcs.GCSFileIO for storageConfiguration GcpStorageConfigurationInfo{storageType=GCS, allowedLocation=[gs://bucket-iceberg-polaris/polaris], gcpServiceAccount=null}","mdc":{"spanId":"0da7f8369a5be134","traceId":"ad635ef2168e9224e25bcb4cfeb587b6","realm":"polaris_iceberg","request_id":null},"params":{}}
{"timestamp":1726172836634,"level":"DEBUG","thread":"pool-3-thread-58 - DELETE /api/catalog/v1/polaris/namespaces/test_schema1/tables/test2?purgeRequested=true","logger":"org.apache.polaris.service.catalog.BasePolarisCatalog","message":"Not initializing default catalogFileIO","mdc":{"spanId":"0da7f8369a5be134","traceId":"ad635ef2168e9224e25bcb4cfeb587b6","realm":"polaris_iceberg","request_id":null},"params":{}}
{"timestamp":1726172836634,"level":"DEBUG","thread":"pool-3-thread-58 - DELETE /api/catalog/v1/polaris/namespaces/test_schema1/tables/test2?purgeRequested=true","logger":"org.apache.polaris.service.catalog.BasePolarisCatalog","message":"new BasePolarisTableOperations for test_schema1.test2","mdc":{"spanId":"0da7f8369a5be134","traceId":"ad635ef2168e9224e25bcb4cfeb587b6","realm":"polaris_iceberg","request_id":null},"params":{}}
{"timestamp":1726172836634,"level":"DEBUG","thread":"pool-3-thread-58 - DELETE /api/catalog/v1/polaris/namespaces/test_schema1/tables/test2?purgeRequested=true","logger":"org.apache.polaris.service.catalog.BasePolarisCatalog","message":"doRefresh for tableIdentifier test_schema1.test2","mdc":{"spanId":"0da7f8369a5be134","traceId":"ad635ef2168e9224e25bcb4cfeb587b6","realm":"polaris_iceberg","request_id":null},"params":{}}
{"timestamp":1726172836635,"level":"DEBUG","thread":"pool-3-thread-58 - DELETE /api/catalog/v1/polaris/namespaces/test_schema1/tables/test2?purgeRequested=true","logger":"org.apache.polaris.core.persistence.resolver.PolarisResolutionManifest","message":"Returning resolvedEntities from getPassthroughResolvedPath: [entity:name=polaris;id=11;parentId=0;entityVersion=1;type=CATALOG;subType=NULL_SUBTYPE;internalProperties={catalogType=INTERNAL, storage_configuration_info={\"@type\":\"GcpStorageConfigurationInfo\",\"allowedLocations\":[\"gs://bucket-iceberg-polaris/polaris\"],\"storageType\":\"GCS\",\"fileIoImplClassName\":\"org.apache.iceberg.gcp.gcs.GCSFileIO\"}};grantRecordsAsGrantee:[];grantRecordsAsSecurable:[PolarisGrantRec{securableCatalogId=0, securableId=11, granteeCatalogId=11, granteeId=12, privilegeCode=2}, PolarisGrantRec{securableCatalogId=0, securableId=11, granteeCatalogId=11, granteeId=12, privilegeCode=31}, PolarisGrantRec{securableCatalogId=0, securableId=11, granteeCatalogId=11, granteeId=12, privilegeCode=32}], entity:name=test_schema1;id=13;parentId=11;entityVersion=1;type=NAMESPACE;subType=NULL_SUBTYPE;internalProperties={};grantRecordsAsGrantee:[];grantRecordsAsSecurable:[], entity:name=test2;id=15;parentId=13;entityVersion=2;type=TABLE_LIKE;subType=TABLE;internalProperties={metadata-location=gs://bucket-iceberg-polaris/polaris/test_schema1/test2-139045f9cbde4d1f9ef643141621a208/metadata/00001-89250289-fa69-4a2a-870e-441a9f4ad873.metadata.json, parent-namespace=test_schema1};grantRecordsAsGrantee:[];grantRecordsAsSecurable:[]]","mdc":{"spanId":"0da7f8369a5be134","traceId":"ad635ef2168e9224e25bcb4cfeb587b6","realm":"polaris_iceberg","request_id":null},"params":{}}
{"timestamp":1726172836635,"level":"DEBUG","thread":"pool-3-thread-58 - DELETE /api/catalog/v1/polaris/namespaces/test_schema1/tables/test2?purgeRequested=true","logger":"org.apache.polaris.service.catalog.BasePolarisCatalog","message":"Refreshing latestLocation: gs://bucket-iceberg-polaris/polaris/test_schema1/test2-139045f9cbde4d1f9ef643141621a208/metadata/00001-89250289-fa69-4a2a-870e-441a9f4ad873.metadata.json","mdc":{"spanId":"0da7f8369a5be134","traceId":"ad635ef2168e9224e25bcb4cfeb587b6","realm":"polaris_iceberg","request_id":null},"params":{}}
{"timestamp":1726172836636,"level":"INFO","thread":"pool-3-thread-58 - DELETE /api/catalog/v1/polaris/namespaces/test_schema1/tables/test2?purgeRequested=true","logger":"org.apache.iceberg.BaseMetastoreTableOperations","message":"Refreshing table metadata from new version: gs://bucket-iceberg-polaris/polaris/test_schema1/test2-139045f9cbde4d1f9ef643141621a208/metadata/00001-89250289-fa69-4a2a-870e-441a9f4ad873.metadata.json","mdc":{"spanId":"0da7f8369a5be134","traceId":"ad635ef2168e9224e25bcb4cfeb587b6","realm":"polaris_iceberg","request_id":null},"params":{}}
{"timestamp":1726172836636,"level":"INFO","thread":"pool-3-thread-58 - DELETE /api/catalog/v1/polaris/namespaces/test_schema1/tables/test2?purgeRequested=true","logger":"org.apache.iceberg.CatalogUtil","message":"Loading custom FileIO implementation: org.apache.iceberg.gcp.gcs.GCSFileIO","mdc":{"spanId":"0da7f8369a5be134","traceId":"ad635ef2168e9224e25bcb4cfeb587b6","realm":"polaris_iceberg","request_id":null},"params":{}}
{"timestamp":1726172836734,"level":"INFO","thread":"pool-3-thread-58 - DELETE /api/catalog/v1/polaris/namespaces/test_schema1/tables/test2?purgeRequested=true","logger":"org.apache.polaris.service.catalog.BasePolarisCatalog","message":"Scheduled cleanup task 16 for table test_schema1.test2","mdc":{"spanId":"0da7f8369a5be134","traceId":"ad635ef2168e9224e25bcb4cfeb587b6","realm":"polaris_iceberg","request_id":null},"params":{}}
{"timestamp":1726172836742,"level":"DEBUG","thread":"pool-3-thread-58 - DELETE /api/catalog/v1/polaris/namespaces/test_schema1/tables/test2?purgeRequested=true","logger":"org.apache.polaris.service.catalog.api.IcebergRestCatalogApi","message":"Completed execution of dropTable API with status code 200","mdc":{"spanId":"0da7f8369a5be134","traceId":"ad635ef2168e9224e25bcb4cfeb587b6","realm":"polaris_iceberg","request_id":null},"params":{}}
{"timestamp":1726172836743,"level":"INFO","thread":"pool-3-thread-58","logger":"io.opentelemetry.exporter.logging.LoggingSpanExporter","message":"'DELETE /api/catalog/v1/polaris/namespaces/test_schema1/tables/test2' : ad635ef2168e9224e25bcb4cfeb587b6 0da7f8369a5be134 SERVER [tracer: /api/catalog/v1/polaris/namespaces/test_schema1/tables/test2:] AttributesMap{data={realm=polaris_iceberg, url.scheme=http, server.address=polaris, url.path=/api/catalog/v1/polaris/namespaces/test_schema1/tables/test2, http.request.method=DELETE}, capacity=128, totalAddedValues=5}","mdc":{"request_id":null,"realm":"polaris_iceberg"},"params":{}}
{"timestamp":1726172836746,"level":"DEBUG","thread":"taskHandler-2","logger":"org.apache.polaris.core.storage.cache.StorageCredentialCache","message":"StorageCredentialCache::load","params":{}}
{"timestamp":1726172837097,"level":"INFO","thread":"taskHandler-2","logger":"org.apache.iceberg.CatalogUtil","message":"Loading custom FileIO implementation: org.apache.iceberg.gcp.gcs.GCSFileIO","params":{}}
{"timestamp":1726172837587,"level":"INFO","thread":"taskHandler-3","logger":"org.apache.iceberg.CatalogUtil","message":"Loading custom FileIO implementation: org.apache.iceberg.gcp.gcs.GCSFileIO","params":{}}
{"timestamp":1726172837671,"level":"INFO","thread":"taskHandler-2","logger":"org.apache.polaris.service.task.TaskExecutorImpl","message":"Task successfully handled","params":{"handlerClass":"org.apache.polaris.service.task.TableCleanupTaskHandler","taskEntityId":16}}
{"timestamp":1726172837976,"level":"DEBUG","thread":"taskHandler-3","logger":"org.apache.polaris.service.task.ManifestFileCleanupTaskHandler","message":"Scheduled 4 data files to be deleted from manifest gs://bucket-iceberg-polaris/polaris/test_schema1/test2-139045f9cbde4d1f9ef643141621a208/metadata/f9449a04-12db-4360-a6fe-f577830d075a-m0.avro","params":{}}
{"timestamp":1726172838303,"level":"INFO","thread":"","logger":"org.apache.polaris.service.task.ManifestFileCleanupTaskHandler","message":"All data files in manifest deleted - deleting manifest","params":{"manifestFile":"gs://bucket-iceberg-polaris/polaris/test_schema1/test2-139045f9cbde4d1f9ef643141621a208/metadata/f9449a04-12db-4360-a6fe-f577830d075a-m0.avro"}}
{"timestamp":1726172838478,"level":"INFO","thread":"taskHandler-3","logger":"org.apache.polaris.service.task.TaskExecutorImpl","message":"Task successfully handled","params":{"handlerClass":"org.apache.polaris.service.task.ManifestFileCleanupTaskHandler","taskEntityId":18}}
```

### System information

Trino 449
Polaris git: 6fcf5ccaebd7ca13a0cb96c96adca699a24080a0

### PR DESCRIPTION
**Pull request by danielhumanmod**
# Description
Currently, when handling DROP TABLE PURGE, Polaris only deletes data files and the current metadata in `TableCleanupTaskHandler`. However, other related files, such as historical metadata.json files, stat files, and others, are not deleted.

Iceberg has addressed this issue (see [Iceberg PR #9305](https://github.com/apache/iceberg/pull/9305)), but Polaris doesn’t adopt this solution due to factors like asynchronous deletion. This PR introduces additional deletions for the following files:

- Previous metadata files
- Statistic files

Fixes #289 

**Included Changes**
- Updated `TableCleanupTaskHandler.java` to schedule previous metadata and statistics deletion in batch
- Extended `ManifestFileCleanupTaskHandler` to delete metadata and statistics file batch
- Extended `TaskTestUtils.java` to write metadata with previous metadata and statistics files
- Add unit tests in `TableCleanupTaskHandlerTest.java` and `TableContentCleanupTaskHandlerTest`

**Recommended Review Order**:
`TableCleanupTaskHandler.java` ->  `ManifestFileCleanupTaskHandler.java` -> `TaskTestUtils.java` -> `TableCleanupTaskHandlerTest.java` and `ManifestFileCleanupTaskHandlerTest`

## Future Improvement
1. [Refactoring] Separate manifest files and metadata file batch, but with a common base class
2. [Feature] Add async deletion partition statistics files

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Documentation update
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Unit Test:
- [x] TableCleanupTaskHandlerTest
- [x] ManifestFileCleanupTaskHandlerTest 

# Checklist:

Please delete options that are not relevant.

- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] If adding new functionality, I have discussed my implementation with the community using the linked GitHub issue

### CODE REVIEW

File: polaris-service/src/main/java/org/apache/polaris/service/task/TableCleanupTaskHandler.java [hunk 1]
```diff
@@ -158,6 +160,22 @@ public boolean handleTask(TaskEntity cleanupTask) {
...
+
+        tableMetadata.snapshots().stream()
+            .flatMap(sn -> sn.allManifests(fileIO).stream())
+            // remove duplication
+            .collect(Collectors.toMap(ManifestFile::path, Function.identity(), (mf1, mf2) -> mf1))
+            .keySet()
+            .forEach(fileIO::deleteFile);
+        tableMetadata.snapshots().stream()
+            .map(Snapshot::manifestListLocation)
+            .forEach(fileIO::deleteFile);
```
Comment (flyrain) [inline polaris-service/src/main/java/org/apache/polaris/service/task/TableCleanupTaskHandler.java:172]: I think we've already handled the manifest list files.

Comment (danielhumanmod) [reply polaris-service/src/main/java/org/apache/polaris/service/task/TableCleanupTaskHandler.java]: > I think we've already handled the manifest files and manifest list files.

Thank you for pointing that out! I just notice that these are already handled in the `ManifestFileCleanupTaskHandler`. I’ve removed the redundant deletion logic in the latest commit.

File: polaris-service/src/main/java/org/apache/polaris/service/task/TableCleanupTaskHandler.java [hunk 2]
```diff
@@ -158,6 +159,13 @@ public boolean handleTask(TaskEntity cleanupTask) {
         for (PolarisBaseEntity createdTask : createdTasks) {
           taskExecutor.addTaskHandlerContext(createdTask.getId(), CallContext.getCurrentContext());
         }
+
+        tableMetadata.previousFiles().stream()
+            .map(TableMetadata.MetadataLogEntry::file)
+            .forEach(fileIO::deleteFile);
+        tableMetadata.statisticsFiles().stream()
+            .map(StatisticsFile::path)
+            .forEach(fileIO::deleteFile);
```
Comment (collado-mike) [inline polaris-service/src/main/java/org/apache/polaris/service/task/TableCleanupTaskHandler.java:168]: We should either add retries for these or submit them as separate tasks. As is, if one of these files fails to delete, we'll retry the whole task and resubmit a new task for each manifest. If the manifests are already deleted when we retry, we'll get stuck in a retry loop.

**Review by collado-mike — CHANGES_REQUESTED** [review]

File: polaris-service/src/main/java/org/apache/polaris/service/task/TableCleanupTaskHandler.java (hunk 2 above)
Comment (danielhumanmod) [reply polaris-service/src/main/java/org/apache/polaris/service/task/TableCleanupTaskHandler.java:168]: Thanks for the suggestion, Michael! I could refactor the process by deleting these files in a new task and executing them separately, similar to how we handle manifest file deletions. Does that align with what you recommended approach?

Comment (collado-mike) [reply polaris-service/src/main/java/org/apache/polaris/service/task/TableCleanupTaskHandler.java:168]: Sorry, do you mean adding retry within the `TableCleanupTaskHandler.java`? If so, that's fine with me. I'd at least use an Executor to attempt the execution in parallel (i.e., so file2 isn't blocked during the delay between retries for file1).

TBH, I'm not very familiar with how Iceberg generates the statistic files. Does there tend to be one per snapshot? one per data file? If the latter, we could be talking about a very large number of files. If that's the case, I think submitting separate tasks with batches of files makes sense.

Comment (flyrain) [reply polaris-service/src/main/java/org/apache/polaris/service/task/TableCleanupTaskHandler.java:168]: They are per snapshots, https://iceberg.apache.org/spec/#table-statistics.

Comment (collado-mike) [reply polaris-service/src/main/java/org/apache/polaris/service/task/TableCleanupTaskHandler.java:168]: Is there only one statistics file per snapshot? The spec is not clear:
> A table can contain many statistics files associated with different table snapshots.

Unlike the partition statistics file, which is very clear:
> Each table snapshot may be associated with at most one partition statistics file.

Comment (flyrain) [reply polaris-service/src/main/java/org/apache/polaris/service/task/TableCleanupTaskHandler.java:168]: Could be multiple statistics files as the following code shows:

https://github.com/apache/iceberg/blob/5439cbdb278232779fdd9a392bbf57f007f9bda0/core/src/main/java/org/apache/iceberg/TableMetadata.java#L535-L535

Comment (danielhumanmod) [reply polaris-service/src/main/java/org/apache/polaris/service/task/TableCleanupTaskHandler.java:168]: > They are per snapshots, https://iceberg.apache.org/spec/#table-statistics.

> Could be multiple statistics files as the following code shows:
> 
> https://github.com/apache/iceberg/blob/5439cbdb278232779fdd9a392bbf57f007f9bda0/core/src/main/java/org/apache/iceberg/TableMetadata.java#L535-L535

Thank you for providing the context, @flyrain :)

> Sorry, do you mean adding retry within the `TableCleanupTaskHandler.java`? If so, that's fine with me. I'd at least use an Executor to attempt the execution in parallel (i.e., so file2 isn't blocked during the delay between retries for file1).
> 
> TBH, I'm not very familiar with how Iceberg generates the statistic files. Does there tend to be one per snapshot? one per data file? If the latter, we could be talking about a very large number of files. If that's the case, I think submitting separate tasks with batches of files makes sense.

@collado-mike Yes, if we go for retries, the logic will be within `TableCleanupTaskHandler.java`. But considering the information provided by Yufei, maybe separate tasks will be a more appropriate approach for stats file deletion?

File: polaris-service/src/test/java/org/apache/polaris/service/task/TableCleanupTaskHandlerTest.java [hunk 3]
```diff
@@ -97,22 +105,30 @@ public void testTableCleanup() throws IOException {
       assertThat(
               metaStoreManagerFactory
                   .getOrCreateMetaStoreManager(realmContext)
-                  .loadTasks(polarisCallContext, "test", 1)
+                  .loadTasks(polarisCallContext, "test", 2)
                   .getEntities())
-          .hasSize(1)
-          .satisfiesExactly(
+          .hasSize(2)
+          .satisfiesExactlyInAnyOrder(
```
Comment (danielhumanmod) [inline polaris-service/src/test/java/org/apache/polaris/service/task/TableCleanupTaskHandlerTest.java:111]: 1. For the single metadata with single snapshot case, verify the ability to delete statistics file

File: polaris-service/src/test/java/org/apache/polaris/service/task/TableCleanupTaskHandlerTest.java [hunk 4]
```diff
@@ -318,21 +345,35 @@ public void testTableCleanupMultipleSnapshots() throws IOException {
...
       CallContext.setCurrentContext(CallContext.of(realmContext, polarisCallContext));
+
       handler.handleTask(task);
 
-      assertThat(
-              metaStoreManagerFactory
-                  .getOrCreateMetaStoreManager(realmContext)
-                  .loadTasks(polarisCallContext, "test", 5)
-                  .getEntities())
+      List<PolarisBaseEntity> entities = metaStoreManagerFactory
```
Comment (danielhumanmod) [inline polaris-service/src/test/java/org/apache/polaris/service/task/TableCleanupTaskHandlerTest.java:351]: 2. For the single metadata with multiple snapshot case, verify the ability to delete all of the statistics files

File: polaris-service/src/test/java/org/apache/polaris/service/task/TableCleanupTaskHandlerTest.java [hunk 5]
```diff
@@ -354,14 +395,207 @@ public void testTableCleanupMultipleSnapshots() throws IOException {
...
+                                              new TableContentCleanupTaskHandler.TableContentCleanupTask(
+                                                      tableIdentifier, statisticsFile2.path()),
+                                              entity -> entity.readData(
+                                                      TableContentCleanupTaskHandler.TableContentCleanupTask.class))
+              );
+    }
+  }
+
+  @Test
+  public void testTableCleanupMultipleMetadata() throws IOException {
```
Comment (danielhumanmod) [inline polaris-service/src/test/java/org/apache/polaris/service/task/TableCleanupTaskHandlerTest.java:436]: 3. For the multiple metadata with multiple snapshot case, verify the ability to delete all of the statistics files and previous metadata

File: polaris-service/src/test/java/org/apache/polaris/service/task/TaskTestUtils.java [hunk 6]
```diff
@@ -62,10 +69,32 @@ static ManifestFile manifestFile(
...
-        TableMetadata.buildFromEmpty()
+    return writeTableMetadata(fileIO, metadataFile, null, null, null, snapshots);
+  }
+
+  static TableMetadata writeTableMetadata(FileIO fileIO, String metadataFile, List<StatisticsFile> statisticsFiles, Snapshot... snapshots)
+          throws IOException {
+    return writeTableMetadata(fileIO, metadataFile, null, null, statisticsFiles, snapshots);
+  }
+
+  static TableMetadata writeTableMetadata(
```
Comment (danielhumanmod) [inline polaris-service/src/test/java/org/apache/polaris/service/task/TaskTestUtils.java:82]: Extend this API to write metadata with previous metadata and statistics file for each snapshot

**Comment by danielhumanmod** [comment]
WIP: process files in batch and add unit test for `TableContentCleanupTask`

File: polaris-service/src/main/java/org/apache/polaris/service/task/TableCleanupTaskHandler.java [hunk 7]
```diff
@@ -49,6 +51,7 @@ public class TableCleanupTaskHandler implements TaskHandler {
   private final TaskExecutor taskExecutor;
   private final MetaStoreManagerFactory metaStoreManagerFactory;
   private final Function<TaskEntity, FileIO> fileIOSupplier;
+  private static final int BATCH_SIZE = 10;
```
Comment (danielhumanmod) [inline polaris-service/src/main/java/org/apache/polaris/service/task/TableCleanupTaskHandler.java:54]: Tentatively set the BATCH_SIZE as 10, please feel free to let me know if there is a better option

**Comment by danielhumanmod** [comment]
Hi @collado-mike @flyrain , I’ve refactored the deletion logic to perform asynchronous deletion in batches, with each batch handled in separate tasks. I’d appreciate any feedback or suggestions you might have :)

**Comment by danielhumanmod** [comment]
> Hi @collado-mike @flyrain , I’ve refactored the deletion logic to perform asynchronous deletion in batches, with each batch handled in separate tasks. I’d appreciate any feedback or suggestions you might have :)

Hi @collado-mike @flyrain @eric-maynard I wanted to kindly request any feedback or suggestions whenever you have a chance. Thank you in advance for your time :)

File: polaris-service/src/main/java/org/apache/polaris/service/task/TableCleanupTaskHandler.java [hunk 8]
```diff
@@ -158,11 +161,98 @@ public boolean handleTask(TaskEntity cleanupTask) {
...
+            cleanupTask,
+            metaStoreManager,
+            polarisCallContext);
+        scheduleTableContentCleanupTask(
+            tableMetadata.statisticsFiles().stream().map(StatisticsFile::path),
+            CleanupTableContentFileType.STATISTICS,
+            fileIO,
+            cleanupTask,
+            metaStoreManager,
+            polarisCallContext);
```
Comment (flyrain) [inline polaris-service/src/main/java/org/apache/polaris/service/task/TableCleanupTaskHandler.java:179]: We could merge these two method calls. How about collecting the file first, then dispatching them into tasks for deletion? We don't have to distinguish file types while collecting them.

File: polaris-service/src/main/java/org/apache/polaris/service/task/TableContentCleanupTaskHandler.java [hunk 9]
```diff
@@ -0,0 +1,189 @@
...
+import org.apache.iceberg.io.FileIO;
+import org.apache.polaris.core.entity.AsyncTaskType;
+import org.apache.polaris.core.entity.TaskEntity;
+import org.slf4j.Logger;
+import org.slf4j.LoggerFactory;
+
+/**
+ * {@link TaskHandler} responsible for deleting previous metadata and statistics files of a table.
+ */
+public class TableContentCleanupTaskHandler implements TaskHandler {
```
Comment (flyrain) [inline polaris-service/src/main/java/org/apache/polaris/service/task/TableContentCleanupTaskHandler.java:37]: This new class is largely same as class `ManifestFileCleanupTaskHandler`.  Can we try to merge it with `ManifestFileCleanupTaskHandler`?

**Review by flyrain — COMMENTED** [review]
Thanks @danielhumanmod for working on it! left some coments.

File: polaris-service/src/main/java/org/apache/polaris/service/task/ManifestFileCleanupTaskHandler.java [hunk 10]
```diff
@@ -68,58 +70,107 @@ public boolean canHandleTask(TaskEntity task) {
...
-        return true;
-      } catch (InterruptedException e) {
-        LOGGER.error(
-            "Interrupted exception deleting data files from manifest {}", manifestFile.path(), e);
-        throw new RuntimeException(e);
-      } catch (ExecutionException e) {
-        LOGGER.error("Unable to delete data files from manifest {}", manifestFile.path(), e);
-        return false;
-      }
+  private boolean manifestFileCleanUp(
```
Comment (danielhumanmod) [inline polaris-service/src/main/java/org/apache/polaris/service/task/ManifestFileCleanupTaskHandler.java:90]: I refactored the deletion logic for the manifest and its files into a new method; no other changes were made

File: polaris-service/src/main/java/org/apache/polaris/service/task/ManifestFileCleanupTaskHandler.java [hunk 11]
```diff
@@ -68,58 +70,107 @@ public boolean canHandleTask(TaskEntity task) {
...
-        return true;
-      } catch (InterruptedException e) {
-        LOGGER.error(
-            "Interrupted exception deleting data files from manifest {}", manifestFile.path(), e);
-        throw new RuntimeException(e);
-      } catch (ExecutionException e) {
-        LOGGER.error("Unable to delete data files from manifest {}", manifestFile.path(), e);
-        return false;
-      }
+  private boolean cleanUpManifestFile(
```
Comment (danielhumanmod) [inline polaris-service/src/main/java/org/apache/polaris/service/task/ManifestFileCleanupTaskHandler.java:90]: For manifest and all its data, I just refactored the deletion logic into a new method; no other changes were made.

File: polaris-service/src/main/java/org/apache/polaris/service/task/ManifestFileCleanupTaskHandler.java [hunk 12]
```diff
@@ -68,58 +70,107 @@ public boolean canHandleTask(TaskEntity task) {
   @Override
   public boolean handleTask(TaskEntity task) {
     ManifestCleanupTask cleanupTask = task.readData(ManifestCleanupTask.class);
-    ManifestFile manifestFile = decodeManifestData(cleanupTask.getManifestFileData());
     TableIdentifier tableId = cleanupTask.getTableId();
     try (FileIO authorizedFileIO = fileIOSupplier.apply(task)) {
-
```
Comment (danielhumanmod) [inline polaris-service/src/main/java/org/apache/polaris/service/task/ManifestFileCleanupTaskHandler.java:74]: Combine manifest and content file cleanup in the same task, but ensure that each task processes only one type of data (either manifest or content files) at a time.

File: polaris-service/src/main/java/org/apache/polaris/service/task/ManifestFileCleanupTaskHandler.java [hunk 13]
```diff
@@ -42,9 +42,11 @@
...
- * {@link TaskHandler} responsible for deleting all of the files in a manifest and the manifest
- * itself. Since data files may be present in multiple manifests across different snapshots, we
- * assume a data file that doesn't exist is missing because it was already deleted by another task.
+ * {@link TaskHandler} responsible for deleting table files: 1. Manifest files: It contains all the
+ * files in a manifest and the manifest itself. Since data files may be present in multiple
+ * manifests across different snapshots, we assume a data file that doesn't exist is missing because
+ * it was already deleted by another task. 2. Table content files: It contains previous metadata and
+ * statistics files, which are grouped and deleted in batch
  */
 public class ManifestFileCleanupTaskHandler implements TaskHandler {
```
Comment (danielhumanmod) [inline polaris-service/src/main/java/org/apache/polaris/service/task/ManifestFileCleanupTaskHandler.java:51]: Renaming this task will triger lots of relevent changes. If a rename is needed, we may want to handle it in a separate PR to avoid too much changes

File: polaris-service/src/test/java/org/apache/polaris/service/task/ManifestFileCleanupTaskHandlerTest.java [hunk 14]
```diff
@@ -226,4 +233,228 @@ public void deleteFile(String location) {
       assertThatPredicate((String f) -> TaskUtils.exists(f, fileIO)).rejects(dataFile2Path);
     }
   }
+
```
Comment (danielhumanmod) [inline polaris-service/src/test/java/org/apache/polaris/service/task/ManifestFileCleanupTaskHandlerTest.java:236]: The test cases in this file primarily verify theses cleanup:
1. straightforward cleanup
2. cleanup when files do not exist
3. cleanup with retries

File: polaris-service/src/test/java/org/apache/polaris/service/task/TableCleanupTaskHandlerTest.java
Comment (danielhumanmod) [inline polaris-service/src/test/java/org/apache/polaris/service/task/TableCleanupTaskHandlerTest.java:1]: The test cases in this file primarily verify theses scenarios:

1. Cleanup of a single metadata file with a single snapshot
2. Cleanup of a single metadata file across multiple snapshots
3. Cleanup of multiple metadata files across multiple snapshots (New)

File: polaris-service/src/test/java/org/apache/polaris/service/task/TableCleanupTaskHandlerTest.java [hunk 15]
```diff
@@ -76,7 +79,13 @@ public void testTableCleanup() throws IOException {
       TestSnapshot snapshot =
           TaskTestUtils.newSnapshot(fileIO, "manifestList.avro", 1, snapshotId, 99L, manifestFile);
       String metadataFile = "v1-49494949.metadata.json";
-      TaskTestUtils.writeTableMetadata(fileIO, metadataFile, snapshot);
```
Comment (danielhumanmod) [inline polaris-service/src/test/java/org/apache/polaris/service/task/TableCleanupTaskHandlerTest.java:79]: 1. Cleanup of a single metadata file with a single snapshot

File: polaris-service/src/test/java/org/apache/polaris/service/task/TableCleanupTaskHandlerTest.java [hunk 16]
```diff
@@ -303,7 +323,20 @@ public void testTableCleanupMultipleSnapshots() throws IOException {
               manifestFile1,
               manifestFile3); // exclude manifest2 from the new snapshot
       String metadataFile = "v1-295495059.metadata.json";
-      TaskTestUtils.writeTableMetadata(fileIO, metadataFile, snapshot, snapshot2);
```
Comment (danielhumanmod) [inline polaris-service/src/test/java/org/apache/polaris/service/task/TableCleanupTaskHandlerTest.java:306]: 2. Cleanup of a single metadata file across multiple snapshots

File: polaris-service/src/test/java/org/apache/polaris/service/task/TableCleanupTaskHandlerTest.java [hunk 17]
```diff
@@ -318,21 +351,181 @@ public void testTableCleanupMultipleSnapshots() throws IOException {
...
+                          new ManifestFileCleanupTaskHandler.ManifestCleanupTask(
+                              tableIdentifier,
+                              List.of(statisticsFile1.path(), statisticsFile2.path())),
+                          entity ->
+                              entity.readData(
+                                  ManifestFileCleanupTaskHandler.ManifestCleanupTask.class)));
+    }
+  }
+
+  @Test
```
Comment (danielhumanmod) [inline polaris-service/src/test/java/org/apache/polaris/service/task/TableCleanupTaskHandlerTest.java:424]: 3. Cleanup of multiple metadata files across multiple snapshots (New)

**Comment by danielhumanmod** [comment]
> Thanks @danielhumanmod for working on it! left some coments.

Thanks for the suggestions @flyrain , I've updated the code based on your comments and added some comment to help the code easier to understand. I’d appreciate any further feedback, and thanks for your time and patience!

File: polaris-service/src/main/java/org/apache/polaris/service/task/TableCleanupTaskHandler.java [hunk 18]
```diff
@@ -154,15 +190,32 @@ public boolean handleTask(TaskEntity cleanupTask) {
...
+
         fileIO.deleteFile(tableEntity.getMetadataLocation());
 
         return true;
       }
     }
     return false;
   }
+
+  private List<List<String>> getContentFileBatch(TableMetadata tableMetadata, FileIO fileIO) {
```
Comment (flyrain) [inline polaris-service/src/main/java/org/apache/polaris/service/task/TableCleanupTaskHandler.java:207]: The name `contentFile` in Iceberg refers to a data file or a delete file. Let's pick another name to avoid confusion, as metadata files and statistic files are not content files. How about `metadataFile`?

File: polaris-service/src/main/java/org/apache/polaris/service/task/TableCleanupTaskHandler.java [hunk 19]
```diff
@@ -154,15 +190,32 @@ public boolean handleTask(TaskEntity cleanupTask) {
...
+    List<List<String>> result = new ArrayList<>();
+    List<String> contentFiles =
```
Comment (flyrain) [inline polaris-service/src/main/java/org/apache/polaris/service/task/TableCleanupTaskHandler.java:209]: rename here

File: polaris-service/src/main/java/org/apache/polaris/service/task/TableCleanupTaskHandler.java [hunk 20]
```diff
@@ -154,15 +190,32 @@ public boolean handleTask(TaskEntity cleanupTask) {
...
+        Stream.concat(
+                tableMetadata.previousFiles().stream().map(TableMetadata.MetadataLogEntry::file),
+                tableMetadata.statisticsFiles().stream().map(StatisticsFile::path))
+            .filter(file -> TaskUtils.exists(file, fileIO))
```
Comment (flyrain) [inline polaris-service/src/main/java/org/apache/polaris/service/task/TableCleanupTaskHandler.java:213]: Do we need to check the file existence here? It will be checked at delete time, right?

File: polaris-service/src/main/java/org/apache/polaris/service/task/TableCleanupTaskHandler.java [hunk 21]
```diff
@@ -142,8 +146,40 @@ public boolean handleTask(TaskEntity cleanupTask) {
                         // copy the internal properties, which will have storage info
                         .setInternalProperties(cleanupTask.getInternalPropertiesAsMap())
                         .build();
-                  })
-              .toList();
+                  });
+
+      Stream<TaskEntity> contentFileCleanupTasks =
```
Comment (flyrain) [inline polaris-service/src/main/java/org/apache/polaris/service/task/TableCleanupTaskHandler.java:151]: -> `metadataFileCleanupTask`

File: polaris-service/src/main/java/org/apache/polaris/service/task/TableCleanupTaskHandler.java [hunk 22]
```diff
@@ -102,7 +106,7 @@ public boolean handleTask(TaskEntity cleanupTask) {
       // read the manifest list for each snapshot. dedupe the manifest files and schedule a
       // cleanupTask
       // for each manifest file and its data files to be deleted
-      List<TaskEntity> taskEntities =
```
Comment (flyrain) [inline polaris-service/src/main/java/org/apache/polaris/service/task/TableCleanupTaskHandler.java:105]: This method is quite long. Can we split it to multiple methods like this?
```
 var manifestFileCleanupTask = getTaskStream(...);
 var metadataFileCleanupTasks = getTaskEntityStream(cleanupTask, tableMetadata, fileIO, tableEntity, metaStoreManager, polarisCallContext);

var taskEntities = Stream.concat(manifestCleanupTasks, contentFileCleanupTasks).toList();
```

File: polaris-service/src/main/java/org/apache/polaris/service/task/ManifestFileCleanupTaskHandler.java [hunk 23]
```diff
@@ -185,12 +236,18 @@ private CompletableFuture<Void> tryDelete(
   public static final class ManifestCleanupTask {
     private TableIdentifier tableId;
     private String manifestFileData;
+    private List<String> contentFileBatch;
```
Comment (flyrain) [inline polaris-service/src/main/java/org/apache/polaris/service/task/ManifestFileCleanupTaskHandler.java:239]: rename here

File: polaris-service/src/main/java/org/apache/polaris/service/task/ManifestFileCleanupTaskHandler.java [hunk 24]
```diff
@@ -68,58 +70,107 @@ public boolean canHandleTask(TaskEntity task) {
...
+      List<String> contentFileBatch, FileIO fileIO, TableIdentifier tableId) {
+    List<String> validFiles =
+        contentFileBatch.stream().filter(file -> TaskUtils.exists(file, fileIO)).toList();
+    if (validFiles.isEmpty()) {
+      LOGGER
+          .atWarn()
+          .addKeyValue("contentFileBatch", contentFileBatch.toString())
+          .addKeyValue("tableId", tableId)
+          .log("Table content cleanup task scheduled, but the none of the file in batch exists");
+      return true;
```
Comment (flyrain) [inline polaris-service/src/main/java/org/apache/polaris/service/task/ManifestFileCleanupTaskHandler.java:147]: Do we need to warn here if 1 out of 10 files doesn't exist?

File: polaris-service/src/main/java/org/apache/polaris/service/task/ManifestFileCleanupTaskHandler.java [hunk 25]
```diff
@@ -68,58 +70,107 @@ public boolean canHandleTask(TaskEntity task) {
...
+          .addKeyValue("contentFileBatch", contentFileBatch.toString())
+          .addKeyValue("tableId", tableId)
+          .log("Exception detected during content file batch deletion", e);
+    }
+
+    LOGGER
+        .atInfo()
+        .addKeyValue("contentFileBatch", contentFileBatch.toString())
+        .addKeyValue("tableId", tableId)
+        .log("Content file batch deletion has completed");
```
Comment (flyrain) [inline polaris-service/src/main/java/org/apache/polaris/service/task/ManifestFileCleanupTaskHandler.java:171]: We can either remove it or make it debug level. An info level log may not be necessary.

File: polaris-service/src/main/java/org/apache/polaris/service/task/ManifestFileCleanupTaskHandler.java [hunk 26]
```diff
@@ -68,58 +70,107 @@ public boolean canHandleTask(TaskEntity task) {
...
+    try {
+      CompletableFuture<Void> allDeletes =
+          CompletableFuture.allOf(deleteFutures.toArray(new CompletableFuture[0]));
+      allDeletes.join();
+    } catch (Exception e) {
+      LOGGER
+          .atWarn()
+          .addKeyValue("contentFileBatch", contentFileBatch.toString())
+          .addKeyValue("tableId", tableId)
+          .log("Exception detected during content file batch deletion", e);
```
Comment (flyrain) [inline polaris-service/src/main/java/org/apache/polaris/service/task/ManifestFileCleanupTaskHandler.java:164]: Should we throw here?

**Review by flyrain — COMMENTED** [review]
Sorry for the delay, @danielhumanmod. Left some comments.

File: polaris-service/src/main/java/org/apache/polaris/service/task/ManifestFileCleanupTaskHandler.java [hunk 27]
```diff
@@ -42,9 +42,11 @@
...
 
 /**
- * {@link TaskHandler} responsible for deleting all of the files in a manifest and the manifest
- * itself. Since data files may be present in multiple manifests across different snapshots, we
- * assume a data file that doesn't exist is missing because it was already deleted by another task.
+ * {@link TaskHandler} responsible for deleting table files: 1. Manifest files: It contains all the
+ * files in a manifest and the manifest itself. Since data files may be present in multiple
+ * manifests across different snapshots, we assume a data file that doesn't exist is missing because
+ * it was already deleted by another task. 2. Table content files: It contains previous metadata and
+ * statistics files, which are grouped and deleted in batch
```
[the remark this answers is not in the document]
Comment (danielhumanmod) [reply polaris-service/src/main/java/org/apache/polaris/service/task/ManifestFileCleanupTaskHandler.java:49]: > Need to handle the same for partition statistics files also (in this PR or as a follow up) more details: [apache/iceberg#9409](https://github.com/apache/iceberg/pull/9409)

Thanks for your suggestion! Would it be okay to address this in a separate PR avoid making this one too large

File: polaris-service/src/main/java/org/apache/polaris/service/task/TableCleanupTaskHandler.java [hunk 28]
```diff
@@ -154,15 +135,118 @@ public boolean handleTask(TaskEntity cleanupTask) {
...
         }
+
         fileIO.deleteFile(tableEntity.getMetadataLocation());
 
         return true;
       }
     }
     return false;
   }
+
```
Comment (danielhumanmod) [inline polaris-service/src/main/java/org/apache/polaris/service/task/TableCleanupTaskHandler.java:151]: Extract previous manifest task creation into a new method, no new change added

File: polaris-service/src/main/java/org/apache/polaris/service/task/ManifestFileCleanupTaskHandler.java (hunk 27 above)
[the remark this answers is not in the document]
Comment (ajantha-bhat) [reply polaris-service/src/main/java/org/apache/polaris/service/task/ManifestFileCleanupTaskHandler.java]: works for me.

**Review by collado-mike — CHANGES_REQUESTED** [review]
Sorry for the slow iteration cycle, but before we check in, I'd like to split the task type. Splitting the task type now means we have freedom to change the handler class design later, but if we start storing different tasks with the same task type, we won't be able to split the handlers later on.

**Comment by danielhumanmod** [comment]
> Sorry for the slow iteration cycle, but before we check in, I'd like to split the task type. Splitting the task type now means we have freedom to change the handler class design later, but if we start storing different tasks with the same task type, we won't be able to split the handlers later on.

Thanks @collado-mike for the suggestions, which are very helpful in improving the code quality. I’ve already split the task types in the cleanup task handler as the comments suggested and am very willing to refactor this in future PRs. Appreciate any additional feedback you may have

**Review by collado-mike — APPROVED** [review]

**Comment by danielhumanmod** [comment]
Hi @flyrain, I have made some changes based on the suggestion of Michael, do you mind taking another look on this? Thanks!
