### PR TITLE
DefaultContextResolver should respect the defaultRealm configuration

### LINKED ISSUE #281: [BUG] DefaultContextResolver is not using defaultRealm value from the PolarisApplicationConfig
### Is this a possible security vulnerability?

- [X] This is NOT a possible security vulnerability

### Describe the bug

[PolarisApplicationConfig](https://github.com/apache/polaris/blob/cc58730a0c626dba574c2577b32081b17b97b7a8/polaris-service/src/main/java/org/apache/polaris/service/config/PolarisApplicationConfig.java#L117) defines defaultRealm and allows overriding it trough configuration file. [DefaultContextResolver](https://github.com/apache/polaris/blob/cc58730a0c626dba574c2577b32081b17b97b7a8/polaris-service/src/main/java/org/apache/polaris/service/context/DefaultContextResolver.java#L52) ignores a value from the configuration. 

### To Reproduce

0. Setup an eclipse link with a database name which is different from `default-realm`
1. Set `defaultRealm`  in the configuration yaml file
2. Try to connect to get the token without setting `realm` explicitly in the request's headers
3. Polaris returns an error: 
```
FATAL: database 'default-realm' does not exist
```

### Actual Behavior

Configuration setting is not a source of truth for the all components

### Expected Behavior

Configuration setting defines a default value for the all components

### Additional context

_No response_

### System information

_No response_

### PR DESCRIPTION
**Pull request by eric-maynard**
# Description

Previously DefaultContextResolver would always use `default-realm` as the default realm regardless of the configuration for `defaultRealm`. This PR fixes this behavior.

Fixes #281

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Documentation update
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

Please delete options that are not relevant.

- [x] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

### CODE REVIEW

File: polaris-service/src/main/java/org/apache/polaris/service/context/DefaultContextResolver.java [hunk 1]
```diff
@@ -44,12 +44,11 @@
  * <p>Example: principal:data-engineer;password:test;realm:acct123
  */
 @JsonTypeName("default")
-public class DefaultContextResolver
-    implements RealmContextResolver, CallContextResolver, ConfigurationStoreAware {
+public class DefaultContextResolver extends RealmContextResolver
+    implements CallContextResolver, ConfigurationStoreAware {
```
Comment (flyrain) [inline polaris-service/src/main/java/org/apache/polaris/service/context/DefaultContextResolver.java:48]: I believe it's unnecessary to rely on inheritance to access methods from RealmContextResolver. Instead, we can use composition, which I think is more appropriate in this case.

We can start by making the resolver a singleton, and then utilize it as a class field within this context. This approach simplifies the design and avoids the potential pitfalls of an inheritance-based model.

Let me know your thoughts.

File: polaris-service/src/main/java/org/apache/polaris/service/context/RealmContextResolver.java [hunk 2]
```diff
@@ -25,11 +25,21 @@
 import org.apache.polaris.service.config.HasEntityManagerFactory;
 
 @JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "type")
-public interface RealmContextResolver extends Discoverable, HasEntityManagerFactory {
-  RealmContext resolveRealmContext(
+public abstract class RealmContextResolver implements Discoverable, HasEntityManagerFactory {
```
Comment (flyrain) [inline polaris-service/src/main/java/org/apache/polaris/service/context/RealmContextResolver.java:28]: By using composition in the class `DefaultContextResolver`, we can still support multiple implementations of `RealmContextResolver` by still keeping it as an interface, and providing an impl. with detailed logic.

**Review by flyrain — COMMENTED** [review]
Thanks @eric-maynard for working on it!  Left some comments. Let me know if they make sense. Also this changes the behavior a bit, I believe it's worthwhile to add a test.

File: polaris-service/src/main/java/org/apache/polaris/service/config/PolarisApplicationConfig.java [hunk 3]
```diff
@@ -91,6 +91,7 @@ public void setPolarisAuthenticator(
   }
 
   public RealmContextResolver getRealmContextResolver() {
+    realmContextResolver.setDefaultRealm(this.defaultRealm);
     return realmContextResolver;
```
[the remark this answers is not in the document]
Comment (eric-maynard) [reply polaris-service/src/main/java/org/apache/polaris/service/config/PolarisApplicationConfig.java:95]: I'm confused by this suggestion; the linked issue is about users not being able to pass an explicit string default via the config. Are you suggesting that we remove the config?

File: polaris-service/src/main/java/org/apache/polaris/service/context/DefaultContextResolver.java (hunk 1 above)
Comment (eric-maynard) [reply polaris-service/src/main/java/org/apache/polaris/service/context/DefaultContextResolver.java:48]: It's not _necessary_ to rely on inheritance, but DefaultContextResolver _is_ a RealmContextResolver. I don't think composition is more appropriate given the semantic relationship between these types.

File: polaris-service/src/main/java/org/apache/polaris/service/context/RealmContextResolver.java (hunk 2 above)
Comment (eric-maynard) [reply polaris-service/src/main/java/org/apache/polaris/service/context/RealmContextResolver.java:28]: Technically we could still leave it as an interface and keep the inheritance relationship, but it would mean we have to make the implementations implement the default realm logic which seems unnecessary.

File: polaris-service/src/main/java/org/apache/polaris/service/config/PolarisApplicationConfig.java (hunk 3 above)
[the remark this answers is not in the document]
Comment (flyrain) [reply polaris-service/src/main/java/org/apache/polaris/service/config/PolarisApplicationConfig.java:95]: ah, I wasn't clear in the first place. I think we can combine these two configs to one. 
```
realmContextResolver:
  type: default

defaultRealms:
  - default-realm
```
To 
```
realmContextResolver:
  type: default
  defaultRealms: default-realm
 ```

With that, we don't have to keep two fields in the config class, and I think it is a nice way to manage the lifecycle of `realmContextResolver`. It could be immutable object without any setting methods.

File: polaris-service/src/main/java/org/apache/polaris/service/context/DefaultContextResolver.java (hunk 1 above)
Comment (flyrain) [reply polaris-service/src/main/java/org/apache/polaris/service/context/DefaultContextResolver.java:48]: Looked a bit more, composition isn't a good way.  But I also think it's unnecessary to combine two interfaces in one solid class, it's not a blocker for this PR thought. We can fix it later.

File: polaris-service/src/main/java/org/apache/polaris/service/context/RealmContextResolver.java (hunk 2 above)
Comment (flyrain) [reply polaris-service/src/main/java/org/apache/polaris/service/context/RealmContextResolver.java:28]: +1 to keep it as an interface. Please ignore my composition idea.

File: polaris-service/src/main/java/org/apache/polaris/service/config/PolarisApplicationConfig.java (hunk 3 above)
[the remark this answers is not in the document]
Comment (flyrain) [reply polaris-service/src/main/java/org/apache/polaris/service/config/PolarisApplicationConfig.java:95]: If we made the above change, I think we don't have to make the interface change in `RealmContextResolver`. We just need to add a constructor in the class `DefaultContextResolver` like this
```
public DefaultContextResolver( @JsonProperty("defaultRealms") final String defaultRealm) {
    this.defaultRealm = defaultRealm;
}
```

File: polaris-service/src/main/java/org/apache/polaris/service/context/DefaultContextResolver.java [hunk 4]
```diff
@@ -92,14 +92,22 @@ public RealmContext resolveRealmContext(
...
 
+  @Override
+  public void setDefaultRealm(String defaultRealm) {
+    this.defaultRealm = defaultRealm;
+  }
+
+  @Override
+  public String getDefaultRealm() {
+    return this.defaultRealm;
+  }
```
Comment (flyrain) [inline polaris-service/src/main/java/org/apache/polaris/service/context/DefaultContextResolver.java:109]: Can we remove this method if it is only used within this class?

File: polaris-service/src/main/java/org/apache/polaris/service/config/PolarisApplicationConfig.java (hunk 3 above)
[the remark this answers is not in the document]
Comment (eric-maynard) [reply polaris-service/src/main/java/org/apache/polaris/service/config/PolarisApplicationConfig.java:95]: Removing the default constructor is still a breaking change, so is this materially better?

[the remark this answers is not in the document]
Comment (eric-maynard) [reply polaris-service/src/main/java/org/apache/polaris/service/config/PolarisApplicationConfig.java:95]: Also, to be clear, we are not just changing how this works for `DefaultContextResolver` but for all `RealmContextResolver` implementations

File: polaris-service/src/main/java/org/apache/polaris/service/context/DefaultContextResolver.java (hunk 4 above)
Comment (eric-maynard) [reply polaris-service/src/main/java/org/apache/polaris/service/context/DefaultContextResolver.java:109]: I don't think we should keep the setter but not the getter

File: polaris-service/src/main/java/org/apache/polaris/service/config/PolarisApplicationConfig.java (hunk 3 above)
[the remark this answers is not in the document]
Comment (eric-maynard) [reply polaris-service/src/main/java/org/apache/polaris/service/config/PolarisApplicationConfig.java:95]: The `defaultRealm` is just the default realm used by `RealmContextResolver` when the realm cannot be parsed from the request

[the remark this answers is not in the document]
Comment (flyrain) [reply polaris-service/src/main/java/org/apache/polaris/service/config/PolarisApplicationConfig.java:95]: Synced with @eric-maynard offline, we agreed on pushing this break change to another PR.

**Review by flyrain — APPROVED** [review]

**Comment by flyrain** [comment]
Thanks @eric-maynard for the fix!

**Comment by Gerrit-K** [comment]
Hey @flyrain and @eric-maynard, sorry to ask, but did this fix work after all? 🤔  I don't see any unit/integration tests attached to the PR and when I set the attribute in my config (in the Helm chart):
```
polarisServerConfig:
  defaultRealm: something
```
I get an exception on startup:
```
io.dropwizard.configuration.ConfigurationParsingException: /app/config/polaris-server.yml has an error:
  * Failed to parse configuration at: defaultRealm; Cannot invoke "org.apache.polaris.service.context.RealmContextResolver.setDefaultRealm(String)" because "this.realmContextResolver" is null (through reference chain: org.apache.polaris.service.dropwizard.config.PolarisApplicationConfig["defaultRealm"])
    at io.dropwizard.configuration.ConfigurationParsingException$Builder.build(ConfigurationParsingException.java:277)
    at io.dropwizard.configuration.BaseConfigurationFactory.build(BaseConfigurationFactory.java:177)
    at io.dropwizard.configuration.BaseConfigurationFactory.build(BaseConfigurationFactory.java:94)
    at io.dropwizard.core.cli.ConfiguredCommand.parseConfiguration(ConfiguredCommand.java:139)
    at io.dropwizard.core.cli.ConfiguredCommand.run(ConfiguredCommand.java:85)
    at io.dropwizard.core.cli.Cli.run(Cli.java:78)
    at io.dropwizard.core.Application.run(Application.java:94)
    at org.apache.polaris.service.dropwizard.PolarisApplication.main(PolarisApplication.java:153)
Caused by: com.fasterxml.jackson.databind.JsonMappingException: Cannot invoke "org.apache.polaris.service.context.RealmContextResolver.setDefaultRealm(String)" because "this.realmContextResolver" is null (through reference chain: org.apache.polaris.service.dropwizard.config.PolarisApplicationConfig["defaultRealm"])
    at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:402)
    at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:361)
    at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.wrapAndThrow(BeanDeserializerBase.java:1964)
    at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:275)
    at com.fasterxml.jackson.module.blackbird.deser.SuperSonicBeanDeserializer.deserialize(SuperSonicBeanDeserializer.java:155)
    at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:342)
    at com.fasterxml.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:4893)
    at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3036)
    at io.dropwizard.configuration.BaseConfigurationFactory.build(BaseConfigurationFactory.java:148)
    ... 6 more
Caused by: java.lang.NullPointerException: Cannot invoke "org.apache.polaris.service.context.RealmContextResolver.setDefaultRealm(String)" because "this.realmContextResolver" is null
    at org.apache.polaris.service.dropwizard.config.PolarisApplicationConfig.setDefaultRealm(PolarisApplicationConfig.java:312)
    at com.fasterxml.jackson.module.blackbird.deser.SettableStringProperty.set(SettableStringProperty.java:56)
    at com.fasterxml.jackson.module.blackbird.deser.SettableStringProperty.deserializeAndSet(SettableStringProperty.java:41)
    at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:273)
    ... 11 more
```
Am I missing something in the config? Or is this maybe a regression?

**Comment by adutra** [comment]
@Gerrit-K you might be experiencing the bug described in #562.

**Comment by Gerrit-K** [comment]
Oh, you're right! Sorry, I must have somehow missed that 🙇
