### PR TITLE
Do not accept provided technical IDs

### LINKED ISSUE #528: [BUG] Misuse of technical IDs when creating entities
### Is this a possible security vulnerability?

- [X] This is NOT a possible security vulnerability

### Describe the bug

Implementations of operations that _create new_ entities, for example in `PolarisAdminService`, must always generate a _new_ technical ID and not use an _externally_ provided one.

Many places in the code base so something like this:
```java
  public PolarisEntity createCatalog(PolarisEntity entity) {
---
    long id =
        entity.getId() <= 0
            ? metaStoreManager.generateNewEntityId(getCurrentPolarisContext()).getId()
            : entity.getId();
...
    PolarisEntity polarisEntity =
        new PolarisEntity.Builder(entity)
            .setId(id)
            .setCreateTimestamp(System.currentTimeMillis())
            .build();
...
```

The above pattern is error prone and can easily lead to issues like ID collisions later on.

Such implementation must really ensure that
1. the passed in ID is either not present or a not-present value (0)
2. the ID of the new entity must always be generated

### PR DESCRIPTION
**Pull request by snazy**
Fixes #528

### CODE REVIEW

File: service/common/src/main/java/org/apache/polaris/service/admin/PolarisAdminService.java [hunk 1]
```diff
@@ -542,19 +544,17 @@ public PolarisEntity createCatalog(PolarisEntity entity) {
     PolarisAuthorizableOperation op = PolarisAuthorizableOperation.CREATE_CATALOG;
     authorizeBasicRootOperationOrThrow(op);
 
+    checkArgument(entity.getId() == -1, "Entity to be created must have no ID assigned");
```
Comment (jbonofre) [inline service/common/src/main/java/org/apache/polaris/service/admin/PolarisAdminService.java:547]: Do we really need to check argument ? Maybe we can simply ignore/override it ?

**Review by jbonofre — APPROVED** [review]

File: service/common/src/main/java/org/apache/polaris/service/admin/PolarisAdminService.java (hunk 1 above)
Comment (snazy) [reply service/common/src/main/java/org/apache/polaris/service/admin/PolarisAdminService.java:547]: Better give a HTTP/400 back, it's nice information
