### PR TITLE
Replace authentication filters with Quarkus Security

### LINKED ISSUE #1345: Persistence blocking call occurs in event-loop thread in @PreMatching filter
### Describe the bug

`@PreMatching` filters run on Vertx event loop threads. In some cases, we make a blocking call to persistence in a filter, hence blocking the event loop thread, which is strongly discouraged.

This occurs in 
```
PolarisPrincipalAuthenticatorFilter 
PolarisPrincipalRolesProviderFilter
```
and potentially other filters.

### To Reproduce

_No response_

### Actual Behavior

_No response_

### Expected Behavior

_No response_

### Additional context

_No response_

### System information

_No response_

### PR DESCRIPTION
**Pull request by adutra**
Fixes #1345 

Summary of changes:

* `PolarisAuthenticationFilter` becomes `PolarisAuthenticationMechanism` + `PolarisIdentityProvider`
  * `PolarisAuthenticationMechanism` is responsible for extracting the credentials from the request
  * `PolarisIdentityProvider` is responsible for validating the credentials and creating a `SecurityIdentity`
  * The split is required since Quarkus implements security in two steps: extraction then validation.
* `ActiveRolesProviderFilter` becomes `ActiveRolesAugmentor`
  * Its role is to augment the `SecurityIdentity` obtained from `PolarisIdentityProvider` with valid roles
  * Maps quite naturally to Quarkus `SecurityIdentityAugmentor`
* Proactive authentication is disabled
  * It does not work well when CDI context and request-scoped beans are required to perform authentication
  * See https://quarkus.io/guides/security-proactive-authentication#cdi-request-context-activation for details
  * The only downside is that any public endpoint would skip authentication, _even if authentication data is present in the request_. But since the only public endpoint in Polaris is the token endpoint, which _does_ validate the client credentials before issuing a token, this is a non-issue.
* Endpoints were annotated with `@RolesAllowed("**")` to indicate that they are authenticated endpoints, but an authenticated principal is enough
  * Since Polaris has its own authorizer, no specific role is required
  * Otherwise, these endpoints are _technically public_
  * Once the filters are gone, they would become _effectively public_

### CODE REVIEW

File: quarkus/service/src/main/java/org/apache/polaris/service/quarkus/auth/PolarisAuthenticationMechanism.java [hunk 1]
```diff
@@ -0,0 +1,92 @@
...
+import io.vertx.ext.web.RoutingContext;
+import jakarta.annotation.Priority;
+import jakarta.enterprise.context.ApplicationScoped;
+import jakarta.enterprise.inject.Alternative;
+import java.util.Collections;
+import java.util.Set;
+
+/** A custom {@link HttpAuthenticationMechanism} that handles Polaris token authentication. */
+@ApplicationScoped
+@Alternative
```
Comment (dimas-b) [inline quarkus/service/src/main/java/org/apache/polaris/service/quarkus/auth/PolarisAuthenticationMechanism.java:42]: Why `@Alternative`? Will this replace _all_ other mechanisms?

File: server-templates/api.mustache [hunk 2]
```diff
@@ -105,7 +105,8 @@ public class {{classname}}  {
   @{{httpMethod}}{{#subresourceOperation}}
   @Path("{{{path}}}"){{/subresourceOperation}}{{#hasConsumes}}
   @Consumes({ {{#consumes}}"{{{mediaType}}}"{{^-last}}, {{/-last}}{{/consumes}} }){{/hasConsumes}}{{#hasProduces}}
-  @Produces({ {{#produces}}"{{{mediaType}}}"{{^-last}}, {{/-last}}{{/produces}} }){{/hasProduces}}
+  @Produces({ {{#produces}}"{{{mediaType}}}"{{^-last}}, {{/-last}}{{/produces}} }){{/hasProduces}}{{#hasAuthMethods}}
+  {{#authMethods}}{{#isOAuth}}@RolesAllowed("**"){{/isOAuth}}{{/authMethods}}{{/hasAuthMethods}}
```
Comment (dimas-b) [inline server-templates/api.mustache:109]: `@RolesAllowed("**")` LGTM, however, just want to mention that we could take full control of authentication and [deny all requests in the auth Mechanism](https://github.com/projectnessie/nessie/blob/main/servers/quarkus-authn/src/main/java/org/projectnessie/server/authn/NessieAuthMechanism.java#L134) (if we wanted). That would complicate the mechanisms a bit, but would provide extra certainly that no holes are left in the API.

File: quarkus/service/src/main/java/org/apache/polaris/service/quarkus/auth/PolarisAuthenticationMechanism.java [hunk 3]
```diff
@@ -0,0 +1,92 @@
...
+@Priority(1)
+public class PolarisAuthenticationMechanism implements HttpAuthenticationMechanism {
```
Comment (dimas-b) [inline quarkus/service/src/main/java/org/apache/polaris/service/quarkus/auth/PolarisAuthenticationMechanism.java:44]: Should this be under `quarkus/server` perhaps (and the other new auth classes)?

It might be preferable to isolate service code and auth code. Plus, downsteam projects may want to adjust how authentication is down, and adding auth-related beans to the services jar may complicate reuse :thinking:

**Review by dimas-b — COMMENTED** [review]
Nice work overall, @adutra ! Just a few relocation / reuse concerns.

File: quarkus/service/src/main/java/org/apache/polaris/service/quarkus/auth/ActiveRolesAugmentor.java [hunk 4]
```diff
@@ -0,0 +1,67 @@
...
+        identity.getPrincipal(AuthenticatedPolarisPrincipal.class);
+    if (polarisPrincipal == null) {
+      throw new AuthenticationFailedException("No Polaris principal found");
+    }
+    Set<String> validRoleNames = activeRolesProvider.getActiveRoles(polarisPrincipal);
+    return QuarkusSecurityIdentity.builder()
+        .setAnonymous(false)
+        .setPrincipal(polarisPrincipal)
+        .addRoles(validRoleNames)
+        .addCredentials(identity.getCredentials())
```
[the remark this answers is not in the document]
Comment (adutra) [reply quarkus/service/src/main/java/org/apache/polaris/service/quarkus/auth/ActiveRolesAugmentor.java:62]: We don't but in principle the idea is to augment the identity, not to decrease it.

File: quarkus/service/src/main/java/org/apache/polaris/service/quarkus/auth/PolarisAuthenticationMechanism.java [hunk 5]
```diff
@@ -0,0 +1,92 @@
...
+import jakarta.annotation.Priority;
+import jakarta.enterprise.context.ApplicationScoped;
+import jakarta.enterprise.inject.Alternative;
+import java.util.Collections;
+import java.util.Set;
+
+/** A custom {@link HttpAuthenticationMechanism} that handles Polaris token authentication. */
+@ApplicationScoped
+@Alternative
+@Priority(1)
```
[the remark this answers is not in the document]
Comment (adutra) [reply quarkus/service/src/main/java/org/apache/polaris/service/quarkus/auth/PolarisAuthenticationMechanism.java:43]: In fact I can remove `@Priority` completely. There is no other auth mechanism for now.

File: server-templates/api.mustache (hunk 2 above)
Comment (adutra) [reply server-templates/api.mustache:109]: These are imho different things.

You can return a failed Uni holding an unauthorized error from an auth mechanism, but that means no other auth mechanism will be attempted. This may not be desired in Polaris, because imho we are heading towards having many auth mechanisms, so even if mechanism A cannot authenticate, maybe mechanism B can.

`@RolesAllowed` is a way to say: please authenticate the caller before invoking this endpoint. Since proactive auth is disabled, no authentication would happen without this annotation when the endpoint is invoked.

File: quarkus/service/src/main/java/org/apache/polaris/service/quarkus/auth/PolarisAuthenticationMechanism.java (hunk 3 above)
Comment (adutra) [reply quarkus/service/src/main/java/org/apache/polaris/service/quarkus/auth/PolarisAuthenticationMechanism.java:44]: It would cause all tests to fail, since there would be no authentication mechanism present in `polaris-quarkus-service`.

I understand the problem, and indeed I think we should isolate authentication in a dedicated module, but I'd argue that this can be done later. After all, authentication was already being done in `polaris-quarkus-service`, this PR doesn't change this fact.

File: quarkus/service/src/main/java/org/apache/polaris/service/quarkus/auth/ActiveRolesAugmentor.java (hunk 4 above)
[the remark this answers is not in the document]
Comment (dimas-b) [reply quarkus/service/src/main/java/org/apache/polaris/service/quarkus/auth/ActiveRolesAugmentor.java:62]: I guess, I commented on the wrong line :sweat_smile: but I believe there's another place in our code where we produce these credentials fro the HTTP request.

File: server-templates/api.mustache (hunk 2 above)
Comment (dimas-b) [reply server-templates/api.mustache:109]: Fair point.

File: quarkus/service/src/main/java/org/apache/polaris/service/quarkus/auth/PolarisAuthenticationMechanism.java (hunk 3 above)
Comment (dimas-b) [reply quarkus/service/src/main/java/org/apache/polaris/service/quarkus/auth/PolarisAuthenticationMechanism.java:40]: +1 to refactoring in a follow-up PR

**Review by dimas-b — APPROVED** [review]

**Review by collado-mike — APPROVED** [review]

**Comment by adutra** [comment]
Thanks @dimas-b and @collado-mike for the reviews.
