### PR TITLE
Unblock test `listNamespacesWithEmptyNamespace`

### LINKED ISSUE #1272: Unblock test `listNamespacesWithEmptyNamespace`
### Describe the bug

The test `listNamespacesWithEmptyNamespace` in `IcebergCatalogTest` is disabled in #1126 as the expected behavior is not applicable to Polaris.

To unblock, do one of the following:
1. Align Polaris behavior with the superclass by handling empty namespaces the same way, or
2. Modify this test to expect an exception and add a Polaris-specific version.

### To Reproduce

Remove the `@Disabled` annotation and run the test.

### Actual Behavior

The test will fail because Polaris implicitly creates an empty namespace, whereas the test expects the empty namespace to not exist unless the user explicitly creates it.

### Expected Behavior

TBD, needs discussion.

### Additional context

_No response_

### System information

_No response_

### PR DESCRIPTION
**Pull request by liamzwbao**
This PR fixes #1272

In Polaris, the empty namespace implicitly exists by default, see [link](https://github.com/apache/polaris/blob/8b5dfa97a8e50a53412d2ded40f2e4db5a40cc42/service/common/src/main/java/org/apache/polaris/service/catalog/iceberg/IcebergCatalog.java#L490-L493). However, the superclass test assumes that the empty namespace does not exist initially, which causes the test to fail as expected in Polaris. This test was originally introduced in apache/iceberg#9890.

#### Changes in this PR:
- Fix Polaris API including `namespaceExists`, `dropNamespace`, `listTables`, `listViews`

### CODE REVIEW

File: quarkus/service/src/test/java/org/apache/polaris/service/quarkus/catalog/IcebergCatalogTest.java [hunk 1]
```diff
@@ -386,18 +386,27 @@ public Map<String, BaseResult> purgeRealms(Iterable<String> realms) {
...
+  }
+
+  @Test
+  public void listNamespacesWithEmptyNamespaceInPolaris() {
+    catalog().createNamespace(NS);
+
+    Assertions.assertThat(catalog().namespaceExists(Namespace.empty())).isTrue();
+    Assertions.assertThat(catalog().listNamespaces())
+        .contains(NS)
+        .doesNotContain(Namespace.empty());
```
Comment (ebyhr) [inline quarkus/service/src/test/java/org/apache/polaris/service/quarkus/catalog/IcebergCatalogTest.java:406]: Is it possible to use `containsExactly(NS)` instead?

File: quarkus/service/src/test/java/org/apache/polaris/service/quarkus/catalog/IcebergCatalogTest.java [hunk 2]
```diff
@@ -386,18 +386,27 @@ public Map<String, BaseResult> purgeRealms(Iterable<String> realms) {
...
-      1) Align Polaris behavior with the superclass by handling empty namespaces the same way, or
-      2) Modify this test to expect an exception and add a Polaris-specific version.
-      """)
   public void listNamespacesWithEmptyNamespace() {
-    super.listNamespacesWithEmptyNamespace();
+    // In Polaris, the empty namespace implicitly exists by default.
+    // The superclass test assumes the empty namespace does not exist initially,
+    // so running it will fail as expected.
+    Assertions.assertThatThrownBy(super::listNamespacesWithEmptyNamespace)
+        .isInstanceOf(AssertionFailedError.class);
```
Comment (dimas-b) [inline quarkus/service/src/test/java/org/apache/polaris/service/quarkus/catalog/IcebergCatalogTest.java:396]: How is it different from `@Disabled`?

File: quarkus/service/src/test/java/org/apache/polaris/service/quarkus/catalog/IcebergCatalogTest.java (hunk 1 above)
Comment (dimas-b) [inline quarkus/service/src/test/java/org/apache/polaris/service/quarkus/catalog/IcebergCatalogTest.java:406]: This looks like a bug to me. The test clearly indicate that the empty namespace exists, but is not returned when all namespaces are listed.

File: quarkus/service/src/test/java/org/apache/polaris/service/quarkus/catalog/IcebergCatalogTest.java (hunk 2 above)
Comment (liamzwbao) [reply quarkus/service/src/test/java/org/apache/polaris/service/quarkus/catalog/IcebergCatalogTest.java:396]: `@Disabled` skips the test completely, so we won't notice if something changes in the superclass. But if we override the test instead, we can still run it and catch any changes in the future.

File: quarkus/service/src/test/java/org/apache/polaris/service/quarkus/catalog/IcebergCatalogTest.java (hunk 1 above)
Comment (liamzwbao) [reply quarkus/service/src/test/java/org/apache/polaris/service/quarkus/catalog/IcebergCatalogTest.java]: Yes! Thanks for pointing it out.

Comment (liamzwbao) [reply quarkus/service/src/test/java/org/apache/polaris/service/quarkus/catalog/IcebergCatalogTest.java]: I think the reason is that `Namespace.empty()` represents the root namespace in Polaris and is created implicitly. When we call `listNamespaces` without any arg, it returns namespaces under the root—i.e., under `Namespace.empty()`. In this case, we only created `NS`, so it's the only one listed. Since creating an "empty" namespace isn’t something we officially support I guess, there’s no empty namespace under the root empty namespace.

That said, I’m happy to clarify what behavior we actually want here and fix it if it turns out to be a bug.

Comment (liamzwbao) [reply quarkus/service/src/test/java/org/apache/polaris/service/quarkus/catalog/IcebergCatalogTest.java]: One interesting behavior is that we can drop the empty namespace using `catalog().dropNamespace(Namespace.empty())`. But after doing that, we can’t create any new namespaces because it fails, saying the parent namespace doesn't exist. Even worse, we also can’t recreate the empty namespace itself since it's explicitly blocked [here](https://github.com/apache/polaris/blob/8b5dfa97a8e50a53412d2ded40f2e4db5a40cc42/service/common/src/main/java/org/apache/polaris/service/catalog/iceberg/IcebergCatalog.java#L490-L493).

I think we should consider aligning the behavior between creating and dropping the empty namespace anyway.

File: quarkus/service/src/test/java/org/apache/polaris/service/quarkus/catalog/IcebergCatalogTest.java (hunk 2 above)
Comment (dimas-b) [reply quarkus/service/src/test/java/org/apache/polaris/service/quarkus/catalog/IcebergCatalogTest.java:396]: This way we run the test method now will not detect any failures, because they are "expected", right?

What are we actually testing here?

Even asserting that `super::listNamespacesWithEmptyNamespace` fails is not very meaningful because we do not know whether it failed for the reason we think it should fail.

File: quarkus/service/src/test/java/org/apache/polaris/service/quarkus/catalog/IcebergCatalogTest.java (hunk 1 above)
Comment (dimas-b) [reply quarkus/service/src/test/java/org/apache/polaris/service/quarkus/catalog/IcebergCatalogTest.java]: IMHO, `catalog().namespaceExists(Namespace.empty())` should not be `true` (as the Iceberg tests expects).

File: quarkus/service/src/test/java/org/apache/polaris/service/quarkus/catalog/IcebergCatalogTest.java (hunk 2 above)
Comment (liamzwbao) [reply quarkus/service/src/test/java/org/apache/polaris/service/quarkus/catalog/IcebergCatalogTest.java]: Remove the overridden of the test as I fix the empty namespace behavior

File: quarkus/service/src/test/java/org/apache/polaris/service/quarkus/catalog/IcebergCatalogTest.java (hunk 1 above)
Comment (liamzwbao) [reply quarkus/service/src/test/java/org/apache/polaris/service/quarkus/catalog/IcebergCatalogTest.java]: Just checked the `RESTSessionCatalog` implementation in Iceberg, seems like it will throw exception for empty namespaces. Fix the behavior in Polaris to match how `RESTCatalog` handles empty namespaces in Iceberg.

File: quarkus/service/src/test/java/org/apache/polaris/service/quarkus/catalog/IcebergCatalogTest.java [hunk 3]
```diff
@@ -386,18 +387,29 @@ public Map<String, BaseResult> purgeRealms(Iterable<String> realms) {
...
-      2) Modify this test to expect an exception and add a Polaris-specific version.
-      """)
-  public void listNamespacesWithEmptyNamespace() {
-    super.listNamespacesWithEmptyNamespace();
+  public void testEmptyNamespace() {
+    IcebergCatalog catalog = catalog();
+    TableIdentifier tableInRootNs = TableIdentifier.of("table");
+
+    ThrowingCallable createTable = () -> catalog.createTable(tableInRootNs, SCHEMA);
+    Assertions.assertThatThrownBy(createTable).isInstanceOf(NoSuchNamespaceException.class);
```
Comment (dimas-b) [inline quarkus/service/src/test/java/org/apache/polaris/service/quarkus/catalog/IcebergCatalogTest.java:396]: Could you assert the message of this `NoSuchNamespaceException`?

File: service/common/src/main/java/org/apache/polaris/service/catalog/iceberg/IcebergCatalog.java [hunk 4]
```diff
@@ -462,7 +462,7 @@ public boolean dropTable(TableIdentifier tableIdentifier, boolean purge) {
 
   @Override
   public List<TableIdentifier> listTables(Namespace namespace) {
-    if (!namespaceExists(namespace) && !namespace.isEmpty()) {
+    if (!namespaceExists(namespace)) {
       throw new NoSuchNamespaceException(
           "Cannot list tables for namespace. Namespace does not exist: %s", namespace);
```
Comment (dimas-b) [inline service/common/src/main/java/org/apache/polaris/service/catalog/iceberg/IcebergCatalog.java:467]: Maybe add quotes around `%s` (same for views)? The empty namespace will result in an awkward message otherwise.

**Review by dimas-b — COMMENTED** [review]
Thanks, @liamzwbao ! These changes LGTM. Just a couple minor comments.

File: quarkus/service/src/test/java/org/apache/polaris/service/quarkus/catalog/IcebergCatalogTest.java [hunk 5]
```diff
@@ -164,6 +164,7 @@ public Map<String, String> getConfigOverrides() {
       new Schema(
           required(3, "id", Types.IntegerType.get(), "unique ID 🤪"),
           required(4, "data", Types.StringType.get()));
+  protected static final String VIEW_QUERY = "select * from ns1.layer1_table";
```
Comment (dimas-b) [inline quarkus/service/src/test/java/org/apache/polaris/service/quarkus/catalog/IcebergCatalogTest.java:167]: why not `private`? Opening access is easy, closing is hard :)

**Review by liamzwbao — COMMENTED** [review]
@dimas-b Thanks for your review! I have addressed the comments and blocked dropping empty namespace to align with creating empty namespace.

**Review by dimas-b — APPROVED** [review]
