### PR TITLE
Unify equals/hashCode for Index.Element

### LINKED ISSUE #4049: Asymmetric equals methods in `Index.Element` implementations
Following up from #4018 

Original comment: https://github.com/apache/polaris/pull/4018/changes#r2954587783

Test code:
```
  @Test
  void compareWithIndexElem() {
    IndexKey key = IndexKey.key("test");
    DirectIndexElement<Object> d = new DirectIndexElement<>(key, null);
    Index.Element<String> e = Index.Element.of(key, "test");
    assertThat(d.equals(e)).isFalse();
    assertThat(e.equals(d)).isFalse();
  }
```

The first assertion passes, but the second assertion throws a NullPointerException. This indicates that this `.equals()` impl. in non-commutative in general.

### PR DESCRIPTION
**Pull request by dimas-b**
* Convert the old `IndexElem` class to the root of the `Index.Element` class hierarchy

* Consolidate equals/hashCode logic for all sub-classes in `IndexElem`

* Support `null` values via a `protected` method - not exposed to public API callers

* Note: Internal index elements having `null` values are never actually compared in runtime ATM

Fixes #4049

## Checklist
- [x] 🛡️ Don't disclose security issues! (contact security@apache.org)
- [x] 🔗 Clearly explained why the changes are needed, or linked related issues: Fixes #
- [ ] 🧪 Added/updated tests with good coverage, or manually tested (and explained how)
- [ ] 💡 Added comments for complex logic
- [ ] 🧾 Updated `CHANGELOG.md` (if needed)
- [ ] 📚 Updated documentation in `site/content/in-dev/unreleased` (if needed)

### CODE REVIEW

File: persistence/nosql/persistence/api/src/main/java/org/apache/polaris/persistence/nosql/api/index/IndexElem.java [hunk 1]
```diff
@@ -58,8 +73,9 @@ public boolean equals(Object o) {
     if (o == this) {
       return true;
     }
-    if (o instanceof Index.Element<?> other) {
-      return key.equals(other.key()) && value.equals(other.value());
+    if (o instanceof IndexElem<?> other) {
```
Comment (jbonofre) [inline persistence/nosql/persistence/api/src/main/java/org/apache/polaris/persistence/nosql/api/index/IndexElem.java:81]: For context (if other reviewers are asking), this is a change in the semantic here.
The "old" `IndexElem` (record) compared against any `Index.Element<?>`, but the new implementation only matches `instanceof IndexElem<?>`. This means a third-party `Index.Element` implementation that isn't an `IndexElem` subclass will no longer be considered equal, even with the same key/value.

The "old" `AbstractIndexElement` also had a fallback to `Index.Element<?>`.

This is an intentional "breaking change". Maybe worth to add a comment here to avoid "surprising" the reviewers 😄

**Review by jbonofre — APPROVED** [review]

File: persistence/nosql/persistence/api/src/main/java/org/apache/polaris/persistence/nosql/api/index/IndexElem.java (hunk 1 above)
Comment (dimas-b) [reply persistence/nosql/persistence/api/src/main/java/org/apache/polaris/persistence/nosql/api/index/IndexElem.java:81]: Good point about the comment - will add.

Re: "breaking changes", the code affected by this PR has not been released yet. Do we want to be so strict about changes between individual commits?

Comment (dimas-b) [reply persistence/nosql/persistence/api/src/main/java/org/apache/polaris/persistence/nosql/api/index/IndexElem.java:81]: comments added

Comment (jbonofre) [reply persistence/nosql/persistence/api/src/main/java/org/apache/polaris/persistence/nosql/api/index/IndexElem.java:81]: It's all good, thanks !
