### PR TITLE
When a grant already exists, return the appropriate response

### LINKED ISSUE #226: [BUG] creating an existing principal role assignment returns 500 instead of 409
### Is this a possible security vulnerability?

- [X] This is NOT a possible security vulnerability

### Describe the bug

When I try to assign between a principal role and a principal I get 2xx.
If I try to run the same assignment again (conflict) I will get 5xx.

### To Reproduce

1. Create a principal.
2. Create a principal role.
3. Assign role to principal.
4. Assign role to principal (again).

### Actual Behavior

500 error.

```
{
    "error": {
        "message": "Exception [EclipseLink-4002] (Eclipse Persistence Services - 4.0.3.v202405220658): org.eclipse.persistence.exceptions.DatabaseException\nInternal Exception: org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint \"grant_records_pkey\"\n  Detail: Key (granteecatalogid, privilegecode, granteeid, securableid, securablecatalogid)=(0, 4, 1599, 1149, 0) already exists.\nError Code: 0\nCall: INSERT INTO GRANT_RECORDS (GRANTEECATALOGID, PRIVILEGECODE, GRANTEEID, SECURABLEID, SECURABLECATALOGID, VERSION) VALUES (?, ?, ?, ?, ?, ?)\n\tbind => [0, 4, 1599, 1149, 0, 1]\nQuery: InsertObjectQuery(org.apache.polaris.core.persistence.models.ModelGrantRecord@5780643b)",
        "type": "PersistenceException",
        "code": 500
    }
}
```

### Expected Behavior

409 - conflict.

### Additional context

_No response_

### System information

N/A

### PR DESCRIPTION
**Pull request by eric-maynard**
# Description

In the event that the persistence layer fails due to a primary key conflict, we should translate this to an AlreadyExistException which maps to response 409. Currently, we are returning a 500.

Fixes #226 

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Documentation update
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

As we don't have a robust test setup for eclipselink-backed Polaris currently, I manually tested with the following setup:

```
      <property name="jakarta.persistence.jdbc.url"
        value="jdbc:postgresql://localhost:5432/db"/>
      <property name="jakarta.persistence.jdbc.user" value="polaris"/>
      <property name="jakarta.persistence.jdbc.password" value="test"/>
      <property name="jakarta.persistence.schema-generation.database.action" value="create"/>
      <property name="eclipselink.logging.level.sql" value="FINE"/>
      <property name="eclipselink.logging.parameters" value="true"/>
      <property name="eclipselink.persistence-context.flush-mode" value="auto"/>
```

I then created a duplicate grant:
```
./polaris \
      --access-token 'principal:root;realm:default-realm' \
      catalogs \
      create example_catalog \
      --storage-type file \
      --default-base-location 'file:///tmp/example'

./polaris \
      --access-token 'principal:root;realm:default-realm' \
      principals \
      create \
      example_user

./polaris \
      --access-token 'principal:root;realm:default-realm' \
      principal-roles \
      create \
      example_user_role

./polaris \
      --access-token 'principal:root;realm:default-realm' \
      principal-roles \
      grant \
      --principal example_user \
      example_user_role

./polaris \
      --access-token 'principal:root;realm:default-realm' \
      principal-roles \
      grant \
      --principal example_user \
      example_user_role
```

This PR fixes the 500 and causes Polaris to return a 409:
```
./polaris \
>       --access-token 'principal:root;realm:default-realm' \
>       principal-roles \
>       grant \
>       --principal example_user \
>       example_user_role
Exception when communicating with the Polaris server. AlreadyExistsException: Grant already exists
```

# Checklist:

Please delete options that are not relevant.

- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings

### CODE REVIEW

File: extension/persistence/eclipselink/src/main/java/org/apache/polaris/extension/persistence/impl/eclipselink/PolarisEclipseLinkMetaStoreSessionImpl.java [hunk 1]
```diff
@@ -257,6 +259,12 @@ public <T> T runInTransaction(
       } finally {
         localSession.remove();
       }
+    } catch (PersistenceException e) {
+      if (e.toString().toLowerCase(Locale.ROOT).contains("duplicate key")) {
+        throw new IllegalStateException("Duplicate key error when persisting entity", e);
```
Comment (eric-maynard) [inline extension/persistence/eclipselink/src/main/java/org/apache/polaris/extension/persistence/impl/eclipselink/PolarisEclipseLinkMetaStoreSessionImpl.java:264]: `PersistenceException` is not visible in the service, and Iceberg's `AlreadyExistsException` is not visible here. It might be ideal to introduce our own exception mapper with our own exceptions kept in polaris-core, but that's a big migration. 

For now, I'm using this `IllegalStateException` to negotiate between the two exception types.

Comment (dennishuo) [reply extension/persistence/eclipselink/src/main/java/org/apache/polaris/extension/persistence/impl/eclipselink/PolarisEclipseLinkMetaStoreSessionImpl.java:264]: It looks like we do already have some specializations for specific jakarta exceptions in [IcebergExceptionMapper](https://github.com/apache/polaris/blob/8f14363abc42ea6d95b67bc407f825b0af9bb4f6/polaris-service/src/main/java/org/apache/polaris/service/IcebergExceptionMapper.java#L71) such as for:

    case jakarta.ws.rs.ForbiddenException e -> Response.Status.FORBIDDEN.getStatusCode();

There's also a kind of catch-all for:

    case WebApplicationException e -> e.getResponse().getStatus();

To avoid throwing a 500 `INTERNAL_SERVER_ERROR` maybe we can either throw `jakarta.persistence.EntityExistsException` here and add a case there to translate that into `CONFLICT` or we could throw a generic `WebApplicationException` here with `CONFLICT` status code already set.

File: polaris-service/src/main/java/org/apache/polaris/service/admin/PolarisServiceImpl.java [hunk 2]
```diff
@@ -505,20 +515,23 @@ public Response addGrantToCatalogRole(
...
+        default:
+          LOGGER
+              .atWarn()
+              .addKeyValue("catalog", catalogName)
+              .addKeyValue("role", catalogRoleName)
+              .log("Don't know how to handle privilege grant: {}", grantRequest);
+          return Response.status(Response.Status.BAD_REQUEST).build();
+      }
+    } catch (IllegalStateException e) {
+      throw new AlreadyExistsException("Grant already exists or resolution failed");
```
Comment (dennishuo) [inline polaris-service/src/main/java/org/apache/polaris/service/admin/PolarisServiceImpl.java:534]: If we throw `jakarta.persistence.EntityExistsException` instead we won't need to assume that `IlegalStateException` should translate to `AlreadyExistsException`. In particular, some elements of the MetaStoreManger very well may throw `IllegalStateException` for true illegal states that are server errors and wouldn't make sense to translate into `AlreadyExistsException`.

File: extension/persistence/eclipselink/src/main/java/org/apache/polaris/extension/persistence/impl/eclipselink/PolarisEclipseLinkMetaStoreSessionImpl.java (hunk 1 above)
Comment (eric-maynard) [reply extension/persistence/eclipselink/src/main/java/org/apache/polaris/extension/persistence/impl/eclipselink/PolarisEclipseLinkMetaStoreSessionImpl.java:264]: I like the idea of using `jakarta.persistence.EntityExistsException` but it seems like that dependency might not be there yet. I will try the latter approach.

Screenshot 2024-09-06 at 12 38 38 AM

Comment (eric-maynard) [reply extension/persistence/eclipselink/src/main/java/org/apache/polaris/extension/persistence/impl/eclipselink/PolarisEclipseLinkMetaStoreSessionImpl.java:264]: It seems that `jakarta.ws.rs.WebApplicationException` is also not available right now. I have tightened the catch to reduce the likelihood that a different `IllegalStateException` gets caught here, but I agree that ideally we could just throw a mapped exception here. Perhaps we can add a new exception mapper?

Comment (dennishuo) [reply extension/persistence/eclipselink/src/main/java/org/apache/polaris/extension/persistence/impl/eclipselink/PolarisEclipseLinkMetaStoreSessionImpl.java:264]: Do we still need to catch it just to rethrow in `PolarisServiceImpl`? Seems we should just let it bubble all the way out adn the `IcebergExceptionMapper` will handle it automatically. Or does `IcebergExceptionMapper` not kick in for these for some reason?

Comment (dennishuo) [reply extension/persistence/eclipselink/src/main/java/org/apache/polaris/extension/persistence/impl/eclipselink/PolarisEclipseLinkMetaStoreSessionImpl.java:264]: If the problem is that `IcebergExceptionMapper` can't see `jakarta.persistence`, I think it's reasonable to include `jakarta.persistence` as a dependency there in `polaris-service`.

File: extension/persistence/eclipselink/src/main/java/org/apache/polaris/extension/persistence/impl/eclipselink/PolarisEclipseLinkMetaStoreSessionImpl.java [hunk 3]
```diff
@@ -257,6 +260,12 @@ public <T> T runInTransaction(
       } finally {
         localSession.remove();
       }
+    } catch (PersistenceException e) {
+      if (e.toString().toLowerCase(Locale.ROOT).contains("duplicate key")) {
+        throw new AlreadyExistsException(e, "Duplicate key error when persisting entity");
```
Comment (RussellSpitzer) [inline extension/persistence/eclipselink/src/main/java/org/apache/polaris/extension/persistence/impl/eclipselink/PolarisEclipseLinkMetaStoreSessionImpl.java:265]: Why do we want to throw an Iceberg exception here? This is polaris only right?

Comment (eric-maynard) [reply extension/persistence/eclipselink/src/main/java/org/apache/polaris/extension/persistence/impl/eclipselink/PolarisEclipseLinkMetaStoreSessionImpl.java:265]: The practical reason we use an Iceberg exception is because we already have exception mapping via `IcebergExceptionMapper` for this exception. This exception is currently used throughout Polaris ([e.g.](https://github.com/apache/polaris/blob/81ec424de5bf4e466660b15dca1778026be07e9e/polaris-service/src/main/java/org/apache/polaris/service/catalog/BasePolarisCatalog.java#L1542)) and so I think it's good to be consistent with that.

Comment (aihuaxu) [reply extension/persistence/eclipselink/src/main/java/org/apache/polaris/extension/persistence/impl/eclipselink/PolarisEclipseLinkMetaStoreSessionImpl.java:265]: Do we throw `jakarta.persistence.EntityExistsException` here or general PersistenceException?

Comment (eric-maynard) [reply extension/persistence/eclipselink/src/main/java/org/apache/polaris/extension/persistence/impl/eclipselink/PolarisEclipseLinkMetaStoreSessionImpl.java:265]: It's not a `EntityExistsException` unfortunately.

Comment (dennishuo) [reply extension/persistence/eclipselink/src/main/java/org/apache/polaris/extension/persistence/impl/eclipselink/PolarisEclipseLinkMetaStoreSessionImpl.java:265]: I'd prefer adding the mapping to `IcebergExceptionMapper` and explicitly throwing `jakarta.persistence.EntityExistsException` here. Even though we have some loose leaking between jakarta exceptions vs Iceberg exceptions in some places it'll be nice to start segmenting them better depending on whether the code is agnostic to Iceberg.

Classes that implement Iceberg interfaces directly should stick to Iceberg exceptions, and ideally the metastore layer can be kept as Iceberg-agnostic as possible.

Comment (eric-maynard) [reply extension/persistence/eclipselink/src/main/java/org/apache/polaris/extension/persistence/impl/eclipselink/PolarisEclipseLinkMetaStoreSessionImpl.java:265]: IIRC from our offline discussion the dependency required to do that doesn't exist and we didn't want to add eclipse-link specific dependencies to the service or core modules. Rather, I would be supportive of each module potentially bringing its own exception mapper.

Of course, I think anything is better than a 500. The important thing is that we don't change the client-facing exception. We can always change the type here used to map to that exception

Comment (dennishuo) [reply extension/persistence/eclipselink/src/main/java/org/apache/polaris/extension/persistence/impl/eclipselink/PolarisEclipseLinkMetaStoreSessionImpl.java:265]: Oh I see, didn't realize we hadn't already pulled in `jakarta.persistence-api`. Looks like we do pull it in as a `compileOnly` dependency in `polaris-core` and `polaris-service` already depends on `polaris-core` so it's kind of close.

Looking at the package it seems like the exceptions are indeed in `jakarta.persistence-api` so in theory it just makes the fatjar bigger if we do fully add it as a dependency in `polaris-service` (latest jar appears to just be ~200kB, so it's not *too* bad).

I guess I could go either way in this case.

**Review by dennishuo — APPROVED** [review]

File: extension/persistence/eclipselink/src/main/java/org/apache/polaris/extension/persistence/impl/eclipselink/PolarisEclipseLinkMetaStoreSessionImpl.java (hunk 3 above)
Comment (eric-maynard) [reply extension/persistence/eclipselink/src/main/java/org/apache/polaris/extension/persistence/impl/eclipselink/PolarisEclipseLinkMetaStoreSessionImpl.java:265]: What do you think of letting modules bring their own exception mapper? I feel like that gives us the best of both words: good dependency hygiene and extensibility as new modules introduce new exceptions.

If you think that could work, I'll file an issue and then maybe merge this as-is. Otherwise, I can just add this dependency now too.

Comment (sfc-gh-ygu) [reply extension/persistence/eclipselink/src/main/java/org/apache/polaris/extension/persistence/impl/eclipselink/PolarisEclipseLinkMetaStoreSessionImpl.java:265]: I'd propose to have a Polaris exception mapping in the core module, so that the service module need only map Polaris exceptions to Iceberg exceptions. In that way, we decouple the extension from service module with a bridge from module core.

Comment (eric-maynard) [reply extension/persistence/eclipselink/src/main/java/org/apache/polaris/extension/persistence/impl/eclipselink/PolarisEclipseLinkMetaStoreSessionImpl.java:265]: > We will need to add a new Polaris exception in the core, which we may have to do anyways in the future.

I'm fine doing this, but we already use this AlreadyExistsException in many places. Would you have me refactor them all to use this new Polaris exception? Does that block this PR?

Comment (flyrain) [reply extension/persistence/eclipselink/src/main/java/org/apache/polaris/extension/persistence/impl/eclipselink/PolarisEclipseLinkMetaStoreSessionImpl.java:265]: > we already use this AlreadyExistsException in many places

We can fix that later. I'd still recommend to start create/use a Polaris exception in this PR so that no more new dependency is added to the extension module.

Comment (eric-maynard) [reply extension/persistence/eclipselink/src/main/java/org/apache/polaris/extension/persistence/impl/eclipselink/PolarisEclipseLinkMetaStoreSessionImpl.java]: Okay, I've rebased per the above. Going to close this thread, but let's re-open the discussion as needed on the new diff. Thanks!

File: polaris-service/src/main/java/org/apache/polaris/service/exception/PolarisExceptionMapper.java [hunk 4]
```diff
@@ -0,0 +1,58 @@
...
+
+/**
+ * An {@link ExceptionMapper} implementation for {@link PolarisException}s modeled after {@link
+ * IcebergExceptionMapper}
+ */
+@Provider
+public class PolarisExceptionMapper implements ExceptionMapper<PolarisException> {
+
+  private Response.Status getStatus(PolarisException exception) {
+    if (exception instanceof AlreadyExistsException alreadyExistsException) {
```
Comment (flyrain) [inline polaris-service/src/main/java/org/apache/polaris/service/exception/PolarisExceptionMapper.java:37]: remove `alreadyExistsException` as it doesn't do anything. Wired that compiler doesn't complain.

File: polaris-service/src/main/java/org/apache/polaris/service/exception/PolarisExceptionMapper.java [hunk 5]
```diff
@@ -0,0 +1,58 @@
...
+      return Response.Status.CONFLICT;
+    } else {
+      throw new IllegalArgumentException("No mapping found for " + exception);
```
Comment (flyrain) [inline polaris-service/src/main/java/org/apache/polaris/service/exception/PolarisExceptionMapper.java:40]: Should we throw an `INTERNAL_SERVER_ERROR` here like what IcebergExceptionMapper does?
```
 default -> Response.Status.INTERNAL_SERVER_ERROR.getStatusCode();
```

File: polaris-core/src/main/java/org/apache/polaris/core/exceptions/PolarisException.java [hunk 6]
```diff
@@ -0,0 +1,31 @@
...
+ * Unless required by applicable law or agreed to in writing,
+ * software distributed under the License is distributed on an
+ * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
+ * KIND, either express or implied.  See the License for the
+ * specific language governing permissions and limitations
+ * under the License.
+ */
+package org.apache.polaris.core.exceptions;
+
+/** Used for Polaris-native exceptions */
```
Comment (flyrain) [inline polaris-core/src/main/java/org/apache/polaris/core/exceptions/PolarisException.java:21]: Minor suggestion for the java doc.
```
/**
 * Base class for Polaris-specific runtime exceptions.
 *
 * <p>All custom exceptions in Polaris should extend this class to provide
 * specific error details.
 */
```

**Review by flyrain — COMMENTED** [review]
LGTM overall. Left minor comments.

**Review by flyrain — APPROVED** [review]
+1

**Comment by flyrain** [comment]
Thanks @eric-maynard for the fix. Thanks @RussellSpitzer @dennishuo for the review.
