### PR TITLE
Make each task attempt run in a dedicated CDI request context

### LINKED ISSUE #3203: Possible ContextNotActiveException for TaskFileIOSupplier
### Describe the bug

* Run `RestCatalogFileIntegrationTest`
* Observe error logged by [TaskExecutorImpl](https://github.com/apache/polaris/blob/64b13a9915274a04e82a12c9fdcd095d12797ca0/runtime/service/src/main/java/org/apache/polaris/service/task/TaskExecutorImpl.java#L150):

```
java.util.concurrent.CompletionException: jakarta.enterprise.context.ContextNotActiveException: RequestScoped context was not active when trying to obtain a bean instance for a client proxy of CLASS bean [class=org.apache.polaris.service.task.TaskFileIOSupplier, id=7kBDtfomB8MiW4C8Cl5bNPGxnxg]
	- you can activate the request context for a specific method using the @ActivateRequestContext interceptor binding
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run$$$capture(CompletableFuture.java:1807)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java)
	at --- Async.Stack.Trace --- (captured by IntelliJ IDEA debugger)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.<init>(CompletableFuture.java:1790)
	at java.base/java.util.concurrent.CompletableFuture.asyncRunStage(CompletableFuture.java:1818)
	at java.base/java.util.concurrent.CompletableFuture.runAsync(CompletableFuture.java:2033)
	at org.apache.polaris.service.task.TaskExecutorImpl.tryHandleTask(TaskExecutorImpl.java:145)
	at org.apache.polaris.service.task.TaskExecutorImpl.lambda$tryHandleTask$1(TaskExecutorImpl.java:151)
	at java.base/java.util.concurrent.CompletableFuture$UniComposeExceptionally.tryFire(CompletableFuture.java:1040)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at io.smallrye.context.impl.wrappers.SlowContextualRunnable.run(SlowContextualRunnable.java:19)
	at org.jboss.threads.EnhancedViewExecutor$EnhancedViewExecutorRunnable.run(EnhancedViewExecutor.java:496)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$15.runWith(VertxCoreRecorder.java:650)
	at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2651)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2630)
	at org.jboss.threads.EnhancedQueueExecutor.runThreadBody(EnhancedQueueExecutor.java:1622)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1589)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:11)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:11)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: jakarta.enterprise.context.ContextNotActiveException: RequestScoped context was not active when trying to obtain a bean instance for a client proxy of CLASS bean [class=org.apache.polaris.service.task.TaskFileIOSupplier, id=7kBDtfomB8MiW4C8Cl5bNPGxnxg]
	- you can activate the request context for a specific method using the @ActivateRequestContext interceptor binding
	at io.quarkus.arc.impl.ClientProxies.notActive(ClientProxies.java:76)
	at io.quarkus.arc.impl.ClientProxies.getSingleContextDelegate(ClientProxies.java:32)
	at org.apache.polaris.service.task.TaskFileIOSupplier_ClientProxy.arc$delegate(Unknown Source)
	at org.apache.polaris.service.task.TaskFileIOSupplier_ClientProxy.apply(Unknown Source)
	at org.apache.polaris.service.task.TableCleanupTaskHandler.handleTask(TableCleanupTaskHandler.java:96)
	at org.apache.polaris.service.task.TaskExecutorImpl.handleTask(TaskExecutorImpl.java:187)
	at org.apache.polaris.service.task.TaskExecutorImpl.handleTaskWithTracing(TaskExecutorImpl.java:226)
	at org.apache.polaris.service.task.TaskExecutorImpl.lambda$tryHandleTask$0(TaskExecutorImpl.java:146)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run$$$capture(CompletableFuture.java:1804)
	... 20 more
```

### Additional context

This is probably a side effect of #2974

### System information

_No response_

### PR DESCRIPTION
**Pull request by dimas-b**
Currently, tasks inherit the CDI context from the requests that submitted them, but run asynchronously. Therefore, if the original request context ends, the task may not be able to use the expired beans for that context.

This change makes each task run in its own dedicated CDI request context with `RealmContext` explicitly propagated in `TaskExecutorImpl`.

Test-only error handlers are added to `TaskExecutorImpl` to facilitate detecting task errors during CI.

Fixes #3203

## Checklist
- [ ] 🛡️ Don't disclose security issues! (contact security@apache.org)
- [ ] 🔗 Clearly explained why the changes are needed, or linked related issues: Fixes #
- [ ] 🧪 Added/updated tests with good coverage, or manually tested (and explained how)
- [ ] 💡 Added comments for complex logic
- [ ] 🧾 Updated `CHANGELOG.md` (if needed)
- [ ] 📚 Updated documentation in `site/content/in-dev/unreleased` (if needed)

### CODE REVIEW

**Comment by dimas-b** [comment]
@cccs-cat001 : FYI

File: runtime/service/src/test/java/org/apache/polaris/service/admin/PolarisAuthzTestBase.java [hunk 1]
```diff
@@ -231,13 +232,9 @@ public void before(TestInfo testInfo) {
 
     RealmContext realmContext = testInfo::getDisplayName;
     QuarkusMock.installMockForType(realmContext, RealmContext.class);
+    realmContextHolder.set(realmContext);
     polarisContext = callContext.getPolarisCallContext();
 
-    ContainerRequestContext containerRequestContext = Mockito.mock(ContainerRequestContext.class);
```
Comment (adnanhemani) [inline runtime/service/src/test/java/org/apache/polaris/service/admin/PolarisAuthzTestBase.java:236]: nit: isn't this for Request ID? Is this causing some downstream issues?

**Review by adnanhemani — COMMENTED** [review]
LGTM - just had one question :)

File: runtime/service/src/main/java/org/apache/polaris/service/task/TaskExecutorImpl.java [hunk 2]
```diff
@@ -207,8 +227,12 @@ protected void handleTask(
     }
   }
 
+  @ActivateRequestContext
   protected void handleTaskWithTracing(
       long taskEntityId, CallContext callContext, PolarisEventMetadata eventMetadata, int attempt) {
+    // Note: each call to this method runs in a new CDI request context
+    realmContextHolder.set(callContext.getRealmContext());
```
Comment (snazy) [inline runtime/service/src/main/java/org/apache/polaris/service/task/TaskExecutorImpl.java]:
```suggestion
    var realmId = callContext.getRealmContext().getRealmIdentifier();
    realmContextHolder.set(() -> realmId);
```

Comment (snazy) [reply runtime/service/src/main/java/org/apache/polaris/service/task/TaskExecutorImpl.java]: Actually, the realm-ID needs to be extracted earlier in `tryHandleTask` outside the async schedule

Comment (dimas-b) [reply runtime/service/src/main/java/org/apache/polaris/service/task/TaskExecutorImpl.java]: good point - fixed

File: runtime/service/src/test/java/org/apache/polaris/service/admin/PolarisAuthzTestBase.java (hunk 1 above)
Comment (dimas-b) [reply runtime/service/src/test/java/org/apache/polaris/service/admin/PolarisAuthzTestBase.java:236]: In this PR `ContainerRequestContext` is not longer a CDI bean required by Polaris (see changes in `ServiceProducers`). Therefore, CDI mocks cannot actually be installed for it (test time exception).

In general, this particular test class does not validate request ID handling, so mocking request IDs is not actually necessary in this class.

Moreover, the `Mockito.when(containerRequestContext.getProperty(Mockito.anyString())).thenReturn("request-id-1")` mock was not specific to request IDs (note `anyString`) and in this particular case was likely mocking Realm IDs, which is handled on line 235 now.

Comment (dimas-b) [reply runtime/service/src/test/java/org/apache/polaris/service/admin/PolarisAuthzTestBase.java:236]: @adnanhemani : I'm going to merge for now as it's a bug fix PR and I believe this particular change is fine. I'm open to following up on this on `main`.

Comment (dimas-b) [reply runtime/service/src/test/java/org/apache/polaris/service/admin/PolarisAuthzTestBase.java:236]: Also, I confirmed (locally) that `PolarisAdminServiceAuthzTest` works without this piece of code on `main` too.
