### PR TITLE
fix: Remove info log about deprecated internal method from PolarisConfiguration

### LINKED ISSUE #1666: Self-induced warnings about `catalogConfigUnsafe`
### Describe the bug

Running Polaris Server OOTB:
```
2025-05-23 14:50:04,570 INFO  [org.apa.pol.cor.con.PolarisConfiguration] [,] [,,,] (main) catalogConfigUnsafe is deprecated! Use catalogConfig() instead.
2025-05-23 14:50:04,571 INFO  [org.apa.pol.cor.con.PolarisConfiguration] [,] [,,,] (main) catalogConfigUnsafe is deprecated! Use catalogConfig() instead.
2025-05-23 14:50:04,572 INFO  [org.apa.pol.cor.con.PolarisConfiguration] [,] [,,,] (main) catalogConfigUnsafe is deprecated! Use catalogConfig() instead.
2025-05-23 14:50:04,573 INFO  [org.apa.pol.cor.con.PolarisConfiguration] [,] [,,,] (main) catalogConfigUnsafe is deprecated! Use catalogConfig() instead.
2025-05-23 14:50:04,574 INFO  [org.apa.pol.cor.con.PolarisConfiguration] [,] [,,,] (main) catalogConfigUnsafe is deprecated! Use catalogConfig() instead.
2025-05-23 14:50:04,574 INFO  [org.apa.pol.cor.con.PolarisConfiguration] [,] [,,,] (main) catalogConfigUnsafe is deprecated! Use catalogConfig() instead.
2025-05-23 14:50:04,575 INFO  [org.apa.pol.cor.con.PolarisConfiguration] [,] [,,,] (main) catalogConfigUnsafe is deprecated! Use catalogConfig() instead.
2025-05-23 14:50:04,576 INFO  [org.apa.pol.cor.con.PolarisConfiguration] [,] [,,,] (main) catalogConfigUnsafe is deprecated! Use catalogConfig() instead.
```

No user-provided configuration was used, but Polaris still logs messages about deprecated config. 

This is not nice from the user's perspective.

### To Reproduce

Build and run Polaris Server

### Actual Behavior

_No response_

### Expected Behavior

No log messages about built-in configuration.

### Additional context

_No response_

### System information

_No response_

### PR DESCRIPTION
**Pull request by dimas-b**
Remove the INFO log about calls to this method in Polaris, because users cannot do anything about these messages.

Phasing out old property names requires coordination with users (e.g. release notes), so it is not a matter of merely avoiding calls to that method in Polaris code.

Fixes #1666

### CODE REVIEW

**Review by adutra — DISMISSED** [review]

File: polaris-core/src/main/java/org/apache/polaris/core/config/FeatureConfiguration.java [hunk 1]
```diff
@@ -131,7 +131,7 @@ public static void enforceFeatureEnabledOrThrow(
       PolarisConfiguration.<Boolean>builder()
           .key("ALLOW_EXTERNAL_TABLE_LOCATION")
           .catalogConfig("polaris.config.allow.external.table.location")
-          .catalogConfigUnsafe("allow.external.table.location")
+          .legacyCatalogConfig("allow.external.table.location")
```
Comment (eric-maynard) [inline polaris-core/src/main/java/org/apache/polaris/core/config/FeatureConfiguration.java:134]: I still like `unsafe` because it suggests the unsafe nature of the method -- it's not clear to me what "legacy" means here. It's old, but, what's different about it?

File: polaris-core/src/main/java/org/apache/polaris/core/config/PolarisConfiguration.java [hunk 2]
```diff
@@ -162,13 +162,8 @@ public Builder<T> catalogConfig(String catalogConfig) {
       return this;
     }
 
-    /**
-     * Used to support backwards compatability before there were reserved properties. Usage of this
-     * method should be removed over time.
-     */
-    @Deprecated
```
Comment (eric-maynard) [inline polaris-core/src/main/java/org/apache/polaris/core/config/PolarisConfiguration.java:169]: I know the alerts are annoying, but I think we need to get in the habit of marking things we want to remove as `Deprecated` and would like to keep the annotation

Comment (eric-maynard) [reply polaris-core/src/main/java/org/apache/polaris/core/config/PolarisConfiguration.java:169]: That's not to say we can't change our minds about this btw, just noting this is by design. Maybe bad design :)

Comment (dimas-b) [reply polaris-core/src/main/java/org/apache/polaris/core/config/PolarisConfiguration.java:169]: Annoying to whom? ;) Right now they seems to be very visible to use users, who cannot do anything to "fix" it :shrug:

Comment (eric-maynard) [reply polaris-core/src/main/java/org/apache/polaris/core/config/PolarisConfiguration.java:169]: Only to users building from source. Otherwise, it's meant to be visible to developers -- a reminder & incentive to deprecate the method, not one to just yank the `@Deprecated` annotation.

Comment (eric-maynard) [reply polaris-core/src/main/java/org/apache/polaris/core/config/PolarisConfiguration.java:169]: Looks good! Just want to flag that there is a surviving log [here](https://github.com/apache/polaris/blob/0a484bb32c867178cb2ddac24d1280bab8b34ab6/polaris-core/src/main/java/org/apache/polaris/core/config/PolarisConfigurationStore.java#L132), but IMO we should keep that one because it tells users to stop using the config, rather than developers to stop building Polaris with a method call in place.

**Review by eric-maynard — APPROVED** [review]
LGTM!

File: polaris-core/src/main/java/org/apache/polaris/core/config/PolarisConfiguration.java (hunk 2 above)
Comment (dimas-b) [reply polaris-core/src/main/java/org/apache/polaris/core/config/PolarisConfiguration.java:169]: The "surviving" log is quite appropriate IMHO. It informs the user that _they_ ought to update their table's properties to use the new name.
